# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cnmf_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.setWindowModality(QtCore.Qt.NonModal)
        DockWidget.resize(462, 783)
        DockWidget.setFloating(True)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_24 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_34 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_22.addWidget(self.label_34)
        self.spinBoxGSig = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxGSig.setMinimum(1)
        self.spinBoxGSig.setProperty("value", 5)
        self.spinBoxGSig.setObjectName("spinBoxGSig")
        self.horizontalLayout_22.addWidget(self.spinBoxGSig)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_22, 15, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 12, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.comboBoxInput = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBoxInput.setObjectName("comboBoxInput")
        self.comboBoxInput.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxInput)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxP = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxP.setMinimum(2)
        self.spinBoxP.setMaximum(10)
        self.spinBoxP.setSingleStep(1)
        self.spinBoxP.setProperty("value", 2)
        self.spinBoxP.setObjectName("spinBoxP")
        self.horizontalLayout.addWidget(self.spinBoxP)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.doubleSpinBoxMergeThresh = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxMergeThresh.setMaximum(1.0)
        self.doubleSpinBoxMergeThresh.setSingleStep(0.05)
        self.doubleSpinBoxMergeThresh.setProperty("value", 0.3)
        self.doubleSpinBoxMergeThresh.setObjectName("doubleSpinBoxMergeThresh")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxMergeThresh)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 10, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.spinBoxStrideCNMF = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxStrideCNMF.setMaximum(999)
        self.spinBoxStrideCNMF.setProperty("value", 30)
        self.spinBoxStrideCNMF.setObjectName("spinBoxStrideCNMF")
        self.horizontalLayout_8.addWidget(self.spinBoxStrideCNMF)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 11, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 19, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.doubleSpinBoxRvalThr = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxRvalThr.setMaximum(1.0)
        self.doubleSpinBoxRvalThr.setSingleStep(0.05)
        self.doubleSpinBoxRvalThr.setProperty("value", 0.8)
        self.doubleSpinBoxRvalThr.setObjectName("doubleSpinBoxRvalThr")
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxRvalThr)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_9, 20, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 24, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.spinBoxDecayTime = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxDecayTime.setMinimum(1)
        self.spinBoxDecayTime.setMaximum(999)
        self.spinBoxDecayTime.setProperty("value", 10)
        self.spinBoxDecayTime.setObjectName("spinBoxDecayTime")
        self.horizontalLayout_10.addWidget(self.spinBoxDecayTime)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_10, 25, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdName = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdName.setObjectName("lineEdName")
        self.horizontalLayout_11.addWidget(self.lineEdName)
        self.btnAddToBatchCNMF = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnAddToBatchCNMF.setObjectName("btnAddToBatchCNMF")
        self.horizontalLayout_11.addWidget(self.btnAddToBatchCNMF)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_11, 32, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnExport = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_12.addWidget(self.btnExport)
        self.btnImport = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnImport.setObjectName("btnImport")
        self.horizontalLayout_12.addWidget(self.btnImport)
        self.gridLayout.addLayout(self.horizontalLayout_12, 33, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 14, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_26 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.doubleSpinBoxCNNThr = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxCNNThr.setMaximum(1.0)
        self.doubleSpinBoxCNNThr.setSingleStep(0.05)
        self.doubleSpinBoxCNNThr.setProperty("value", 0.8)
        self.doubleSpinBoxCNNThr.setObjectName("doubleSpinBoxCNNThr")
        self.horizontalLayout_15.addWidget(self.doubleSpinBoxCNNThr)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_15, 22, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 21, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_27 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        self.spinBoxGnb = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxGnb.setMaximum(99)
        self.spinBoxGnb.setProperty("value", 1)
        self.spinBoxGnb.setObjectName("spinBoxGnb")
        self.horizontalLayout_19.addWidget(self.spinBoxGnb)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_19, 4, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_31 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_21.addWidget(self.label_31)
        self.spinBoxK = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxK.setMinimum(1)
        self.spinBoxK.setProperty("value", 10)
        self.spinBoxK.setObjectName("spinBoxK")
        self.horizontalLayout_21.addWidget(self.spinBoxK)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_21, 13, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 16, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.spinBoxRf = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxRf.setMaximum(999)
        self.spinBoxRf.setProperty("value", 50)
        self.spinBoxRf.setObjectName("spinBoxRf")
        self.horizontalLayout_13.addWidget(self.spinBoxRf)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_13, 9, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.doubleSpinBoxMinSNR = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxMinSNR.setMaximum(100.0)
        self.doubleSpinBoxMinSNR.setSingleStep(0.25)
        self.doubleSpinBoxMinSNR.setProperty("value", 2.5)
        self.doubleSpinBoxMinSNR.setObjectName("doubleSpinBoxMinSNR")
        self.horizontalLayout_14.addWidget(self.doubleSpinBoxMinSNR)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_14, 17, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.lineEdName.returnPressed.connect(self.btnAddToBatchCNMF.click)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.comboBoxInput, self.spinBoxP)
        DockWidget.setTabOrder(self.spinBoxP, self.spinBoxStrideCNMF)
        DockWidget.setTabOrder(self.spinBoxStrideCNMF, self.doubleSpinBoxRvalThr)
        DockWidget.setTabOrder(self.doubleSpinBoxRvalThr, self.spinBoxDecayTime)
        DockWidget.setTabOrder(self.spinBoxDecayTime, self.spinBoxRf)
        DockWidget.setTabOrder(self.spinBoxRf, self.spinBoxGnb)
        DockWidget.setTabOrder(self.spinBoxGnb, self.spinBoxK)
        DockWidget.setTabOrder(self.spinBoxK, self.lineEdName)
        DockWidget.setTabOrder(self.lineEdName, self.btnAddToBatchCNMF)
        DockWidget.setTabOrder(self.btnAddToBatchCNMF, self.btnExport)
        DockWidget.setTabOrder(self.btnExport, self.btnImport)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "CNMF"))
        self.label_24.setText(_translate("DockWidget", "Half size of patch in pixels"))
        self.label_34.setText(_translate("DockWidget", "gSig:"))
        self.label_32.setText(_translate("DockWidget", "Number of neurons/cell per patch"))
        self.label_19.setText(_translate("DockWidget", "Input:"))
        self.comboBoxInput.setItemText(0, _translate("DockWidget", "Current Work Environment"))
        self.label.setText(_translate("DockWidget", "p:"))
        self.label_11.setText(_translate("DockWidget", "Merging threshold, max correlation allowed"))
        self.label_10.setText(_translate("DockWidget", "merge_thresh:"))
        self.label_13.setText(_translate("DockWidget", "amount of overlap between the patches in pixels"))
        self.label_12.setText(_translate("DockWidget", "stride_cnmf:"))
        self.label_14.setText(_translate("DockWidget", "Space correlation threshold for accepting a component"))
        self.label_15.setText(_translate("DockWidget", "rval_thr:"))
        self.label_17.setText(_translate("DockWidget", "Average decay time of calcium spikes (seconds)"))
        self.label_16.setText(_translate("DockWidget", "decay_time:"))
        self.lineEdName.setPlaceholderText(_translate("DockWidget", "Enter name"))
        self.btnAddToBatchCNMF.setText(_translate("DockWidget", "Add to batch"))
        self.btnExport.setText(_translate("DockWidget", "Export Parameters"))
        self.btnImport.setText(_translate("DockWidget", "Import Parameters"))
        self.label_22.setText(_translate("DockWidget", "Order of the autoregressive system"))
        self.label_33.setText(_translate("DockWidget", "Expected half size of neurons"))
        self.label_26.setText(_translate("DockWidget", "cnn_thr:"))
        self.label_25.setText(_translate("DockWidget", "Threshold for CNN based classifier"))
        self.label_27.setText(_translate("DockWidget", "gnb:"))
        self.label_31.setText(_translate("DockWidget", "k:"))
        self.label_28.setText(_translate("DockWidget", "Global number of background components"))
        self.label_20.setText(_translate("DockWidget", "Signal to noise ratio for accepting a component"))
        self.label_21.setText(_translate("DockWidget", "rf:"))
        self.label_23.setText(_translate("DockWidget", "min_SNR:"))

