# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './cnmf_3d_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CNMF3D_template(object):
    def setupUi(self, CNMF3D_template):
        CNMF3D_template.setObjectName("CNMF3D_template")
        CNMF3D_template.resize(261, 596)
        CNMF3D_template.setFloating(True)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.spinBox_p = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_p.setProperty("value", 2)
        self.spinBox_p.setObjectName("spinBox_p")
        self.verticalLayout.addWidget(self.spinBox_p)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox_rf = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_rf.setMaximum(9999)
        self.spinBox_rf.setSingleStep(5)
        self.spinBox_rf.setProperty("value", 25)
        self.spinBox_rf.setObjectName("spinBox_rf")
        self.verticalLayout.addWidget(self.spinBox_rf)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox_stride = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_stride.setMaximum(9999)
        self.spinBox_stride.setSingleStep(5)
        self.spinBox_stride.setProperty("value", 15)
        self.spinBox_stride.setObjectName("spinBox_stride")
        self.verticalLayout.addWidget(self.spinBox_stride)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.spinBox_K = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_K.setMaximum(9999)
        self.spinBox_K.setProperty("value", 5)
        self.spinBox_K.setObjectName("spinBox_K")
        self.verticalLayout.addWidget(self.spinBox_K)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_gSig_x = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_gSig_x.setMaximum(999)
        self.spinBox_gSig_x.setProperty("value", 3)
        self.spinBox_gSig_x.setObjectName("spinBox_gSig_x")
        self.horizontalLayout.addWidget(self.spinBox_gSig_x)
        self.spinBox_gSig_y = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_gSig_y.setMaximum(999)
        self.spinBox_gSig_y.setProperty("value", 3)
        self.spinBox_gSig_y.setObjectName("spinBox_gSig_y")
        self.horizontalLayout.addWidget(self.spinBox_gSig_y)
        self.spinBox_gSig_z = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBox_gSig_z.setMaximum(999)
        self.spinBox_gSig_z.setProperty("value", 3)
        self.spinBox_gSig_z.setObjectName("spinBox_gSig_z")
        self.horizontalLayout.addWidget(self.spinBox_gSig_z)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.doubleSpinBox_merge_threshold = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_merge_threshold.setMinimum(0.01)
        self.doubleSpinBox_merge_threshold.setMaximum(1.0)
        self.doubleSpinBox_merge_threshold.setSingleStep(0.01)
        self.doubleSpinBox_merge_threshold.setProperty("value", 0.8)
        self.doubleSpinBox_merge_threshold.setObjectName("doubleSpinBox_merge_threshold")
        self.verticalLayout.addWidget(self.doubleSpinBox_merge_threshold)
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.doubleSpinBox_rval = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_rval.setMaximum(1.0)
        self.doubleSpinBox_rval.setSingleStep(0.01)
        self.doubleSpinBox_rval.setProperty("value", 0.7)
        self.doubleSpinBox_rval.setObjectName("doubleSpinBox_rval")
        self.verticalLayout.addWidget(self.doubleSpinBox_rval)
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.doubleSpinBox_minSNR = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_minSNR.setSingleStep(0.25)
        self.doubleSpinBox_minSNR.setProperty("value", 2.5)
        self.doubleSpinBox_minSNR.setObjectName("doubleSpinBox_minSNR")
        self.verticalLayout.addWidget(self.doubleSpinBox_minSNR)
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.doubleSpinBox_decay_time = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBox_decay_time.setMinimum(0.25)
        self.doubleSpinBox_decay_time.setProperty("value", 2.0)
        self.doubleSpinBox_decay_time.setObjectName("doubleSpinBox_decay_time")
        self.verticalLayout.addWidget(self.doubleSpinBox_decay_time)
        self.checkBox_refit = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox_refit.setObjectName("checkBox_refit")
        self.verticalLayout.addWidget(self.checkBox_refit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_name = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout_2.addWidget(self.lineEdit_name)
        self.pushButton_add_to_batch = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_add_to_batch.setObjectName("pushButton_add_to_batch")
        self.horizontalLayout_2.addWidget(self.pushButton_add_to_batch)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        CNMF3D_template.setWidget(self.dockWidgetContents)

        self.retranslateUi(CNMF3D_template)
        QtCore.QMetaObject.connectSlotsByName(CNMF3D_template)
        CNMF3D_template.setTabOrder(self.spinBox_p, self.spinBox_rf)
        CNMF3D_template.setTabOrder(self.spinBox_rf, self.spinBox_stride)
        CNMF3D_template.setTabOrder(self.spinBox_stride, self.spinBox_K)
        CNMF3D_template.setTabOrder(self.spinBox_K, self.spinBox_gSig_x)
        CNMF3D_template.setTabOrder(self.spinBox_gSig_x, self.spinBox_gSig_y)
        CNMF3D_template.setTabOrder(self.spinBox_gSig_y, self.spinBox_gSig_z)
        CNMF3D_template.setTabOrder(self.spinBox_gSig_z, self.doubleSpinBox_merge_threshold)
        CNMF3D_template.setTabOrder(self.doubleSpinBox_merge_threshold, self.doubleSpinBox_rval)
        CNMF3D_template.setTabOrder(self.doubleSpinBox_rval, self.doubleSpinBox_minSNR)
        CNMF3D_template.setTabOrder(self.doubleSpinBox_minSNR, self.doubleSpinBox_decay_time)
        CNMF3D_template.setTabOrder(self.doubleSpinBox_decay_time, self.checkBox_refit)
        CNMF3D_template.setTabOrder(self.checkBox_refit, self.lineEdit_name)
        CNMF3D_template.setTabOrder(self.lineEdit_name, self.pushButton_add_to_batch)

    def retranslateUi(self, CNMF3D_template):
        _translate = QtCore.QCoreApplication.translate
        CNMF3D_template.setWindowTitle(_translate("CNMF3D_template", "CNMF 3D"))
        self.label_6.setText(_translate("CNMF3D_template", "p"))
        self.label.setText(_translate("CNMF3D_template", "rf"))
        self.label_2.setText(_translate("CNMF3D_template", "stride"))
        self.label_3.setText(_translate("CNMF3D_template", "K"))
        self.label_4.setText(_translate("CNMF3D_template", "gSig, (x, y z)"))
        self.label_5.setText(_translate("CNMF3D_template", "merge threshold"))
        self.label_7.setText(_translate("CNMF3D_template", "rval threshold"))
        self.label_8.setText(_translate("CNMF3D_template", "min SNR"))
        self.label_9.setText(_translate("CNMF3D_template", "decay time"))
        self.checkBox_refit.setText(_translate("CNMF3D_template", "refit"))
        self.lineEdit_name.setPlaceholderText(_translate("CNMF3D_template", "Enter name"))
        self.pushButton_add_to_batch.setText(_translate("CNMF3D_template", "Add to batch"))

