# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/suite2p_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidgetSuite2p(object):
    def setupUi(self, DockWidgetSuite2p):
        DockWidgetSuite2p.setObjectName("DockWidgetSuite2p")
        DockWidgetSuite2p.resize(593, 415)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_dir = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_dir.setObjectName("pushButton_dir")
        self.horizontalLayout_2.addWidget(self.pushButton_dir)
        self.label_dir = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_dir.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_dir.setObjectName("label_dir")
        self.horizontalLayout_2.addWidget(self.label_dir)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_imgseq = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_imgseq.setObjectName("pushButton_imgseq")
        self.horizontalLayout_3.addWidget(self.pushButton_imgseq)
        self.label_imgseq = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_imgseq.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_imgseq.setObjectName("label_imgseq")
        self.horizontalLayout_3.addWidget(self.label_imgseq)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_F = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_F.setObjectName("pushButton_F")
        self.horizontalLayout_4.addWidget(self.pushButton_F)
        self.label_F = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_F.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_F.setObjectName("label_F")
        self.horizontalLayout_4.addWidget(self.label_F)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_stat = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_stat.setObjectName("pushButton_stat")
        self.horizontalLayout_5.addWidget(self.pushButton_stat)
        self.label_stat = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_stat.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_stat.setObjectName("label_stat")
        self.horizontalLayout_5.addWidget(self.label_stat)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_ops = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_ops.setObjectName("pushButton_ops")
        self.horizontalLayout_6.addWidget(self.pushButton_ops)
        self.label_ops = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_ops.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_ops.setObjectName("label_ops")
        self.horizontalLayout_6.addWidget(self.label_ops)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_iscell = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_iscell.setObjectName("pushButton_iscell")
        self.horizontalLayout_7.addWidget(self.pushButton_iscell)
        self.label_iscell = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_iscell.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_iscell.setObjectName("label_iscell")
        self.horizontalLayout_7.addWidget(self.label_iscell)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        DockWidgetSuite2p.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidgetSuite2p)
        QtCore.QMetaObject.connectSlotsByName(DockWidgetSuite2p)

    def retranslateUi(self, DockWidgetSuite2p):
        _translate = QtCore.QCoreApplication.translate
        DockWidgetSuite2p.setWindowTitle(_translate("DockWidgetSuite2p", "S&uite2p importer"))
        self.label_2.setText(_translate("DockWidgetSuite2p", "Select:"))
        self.pushButton_dir.setToolTip(_translate("DockWidgetSuite2p", "Choose a dir containing the suite2p output data and corresponding image sequence"))
        self.pushButton_dir.setText(_translate("DockWidgetSuite2p", "dir"))
        self.label_dir.setText(_translate("DockWidgetSuite2p", "TextLabel"))
        self.pushButton_imgseq.setText(_translate("DockWidgetSuite2p", "img seq"))
        self.label_imgseq.setText(_translate("DockWidgetSuite2p", "TextLabel"))
        self.pushButton_F.setText(_translate("DockWidgetSuite2p", "F.npy"))
        self.label_F.setText(_translate("DockWidgetSuite2p", "TextLabel"))
        self.pushButton_stat.setText(_translate("DockWidgetSuite2p", "stat.npy"))
        self.label_stat.setText(_translate("DockWidgetSuite2p", "TextLabel"))
        self.pushButton_ops.setText(_translate("DockWidgetSuite2p", "ops.npy"))
        self.label_ops.setText(_translate("DockWidgetSuite2p", "TextLabel"))
        self.pushButton_iscell.setText(_translate("DockWidgetSuite2p", "iscell.npy"))
        self.label_iscell.setText(_translate("DockWidgetSuite2p", "TextLabel"))

