# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setEnabled(False)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDataFrame = QtWidgets.QMenu(self.menubar)
        self.menuDataFrame.setEnabled(True)
        self.menuDataFrame.setObjectName("menuDataFrame")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setAcceptDrops(True)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_in_Analyzer = QtWidgets.QAction(MainWindow)
        self.actionOpen_in_Analyzer.setEnabled(True)
        self.actionOpen_in_Analyzer.setObjectName("actionOpen_in_Analyzer")
        self.actionSave_child_as_root = QtWidgets.QAction(MainWindow)
        self.actionSave_child_as_root.setObjectName("actionSave_child_as_root")
        self.actionDelete_Child_from_Project = QtWidgets.QAction(MainWindow)
        self.actionDelete_Child_from_Project.setObjectName("actionDelete_Child_from_Project")
        self.actionProject_Configuration = QtWidgets.QAction(MainWindow)
        self.actionProject_Configuration.setObjectName("actionProject_Configuration")
        self.actionShow_Viewer = QtWidgets.QAction(MainWindow)
        self.actionShow_Viewer.setEnabled(False)
        self.actionShow_Viewer.setObjectName("actionShow_Viewer")
        self.actionNewAnalyzerInstance = QtWidgets.QAction(MainWindow)
        self.actionNewAnalyzerInstance.setCheckable(False)
        self.actionNewAnalyzerInstance.setEnabled(False)
        self.actionNewAnalyzerInstance.setObjectName("actionNewAnalyzerInstance")
        self.actionNew_Viewer_instance = QtWidgets.QAction(MainWindow)
        self.actionNew_Viewer_instance.setObjectName("actionNew_Viewer_instance")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        self.actionConsole.setCheckable(True)
        self.actionConsole.setChecked(False)
        self.actionConsole.setEnabled(True)
        self.actionConsole.setObjectName("actionConsole")
        self.actionHide_Console = QtWidgets.QAction(MainWindow)
        self.actionHide_Console.setEnabled(False)
        self.actionHide_Console.setObjectName("actionHide_Console")
        self.actionNew_Stats_Plots_instance = QtWidgets.QAction(MainWindow)
        self.actionNew_Stats_Plots_instance.setObjectName("actionNew_Stats_Plots_instance")
        self.actionShow_all_Analyzer_windows = QtWidgets.QAction(MainWindow)
        self.actionShow_all_Analyzer_windows.setObjectName("actionShow_all_Analyzer_windows")
        self.actionShow_all_Stats_Plots_windows = QtWidgets.QAction(MainWindow)
        self.actionShow_all_Stats_Plots_windows.setObjectName("actionShow_all_Stats_Plots_windows")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionProject_Configuration)
        self.menuView.addAction(self.actionShow_Viewer)
        self.menuView.addAction(self.actionNew_Viewer_instance)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionNewAnalyzerInstance)
        self.menuView.addAction(self.actionShow_all_Analyzer_windows)
        self.menuView.addAction(self.actionNew_Stats_Plots_instance)
        self.menuView.addAction(self.actionShow_all_Stats_Plots_windows)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionConsole)
        self.menuDataFrame.addAction(self.actionSave_child_as_root)
        self.menuDataFrame.addAction(self.actionDelete_Child_from_Project)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDataFrame.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.actionConsole.toggled['bool'].connect(self.dockWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuDataFrame.setTitle(_translate("MainWindow", "DataFrame"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_in_Analyzer.setText(_translate("MainWindow", "Open in Analyzer"))
        self.actionSave_child_as_root.setText(_translate("MainWindow", "New project from Child"))
        self.actionDelete_Child_from_Project.setText(_translate("MainWindow", "Delete Child from Project"))
        self.actionProject_Configuration.setText(_translate("MainWindow", "Project Configuration"))
        self.actionShow_Viewer.setText(_translate("MainWindow", "Show Viewer(s)"))
        self.actionNewAnalyzerInstance.setText(_translate("MainWindow", "New Analyzer instance"))
        self.actionNew_Viewer_instance.setText(_translate("MainWindow", "New Viewer instance"))
        self.actionConsole.setText(_translate("MainWindow", "Console"))
        self.actionHide_Console.setText(_translate("MainWindow", "Hide Console"))
        self.actionNew_Stats_Plots_instance.setText(_translate("MainWindow", "New Stats/Plots instance"))
        self.actionShow_all_Analyzer_windows.setText(_translate("MainWindow", "Show all Analyzer windows"))
        self.actionShow_all_Stats_Plots_windows.setText(_translate("MainWindow", "Show all Stats/Plots windows"))

