from setuptools import setup

setup(
    name='mesmerize',
    version='0.1',
    packages=['mesmerize', 'mesmerize.common', 'mesmerize.viewer', 'mesmerize.viewer.core', 'mesmerize.viewer.modules',
              'mesmerize.viewer.modules.custom_modules', 'mesmerize.viewer.modules.stimmap_modules',
              'mesmerize.viewer.modules.batch_run_modules', 'mesmerize.viewer.modules.roi_manager_modules',
              'mesmerize.viewer.modules.roi_manager_modules.read_imagej', 'mesmerize.viewer.image_menu',
              'mesmerize.viewer.image_utils', 'mesmerize.analysis', 'mesmerize.analysis.pytemplates',
              'mesmerize.plotting', 'mesmerize.plotting.widgets', 'mesmerize.plotting.widgets.lda',
              'mesmerize.plotting.widgets.kshape', 'mesmerize.plotting.widgets.heatmap',
              'mesmerize.plotting.widgets.scatter', 'mesmerize.plotting.widgets.beeswarms',
              'mesmerize.plotting.widgets.peak_editor', 'mesmerize.plotting.widgets.plot_window',
              'mesmerize.plotting.widgets.cross_correlation', 'mesmerize.plotting.widgets.curve_plot_window',
              'mesmerize.plotting.variants', 'mesmerize.misc_widgets', 'mesmerize.pyqtgraphCore',
              'mesmerize.pyqtgraphCore.util', 'mesmerize.pyqtgraphCore.util.colorama', 'mesmerize.pyqtgraphCore.tests',
              'mesmerize.pyqtgraphCore.canvas', 'mesmerize.pyqtgraphCore.opengl',
              'mesmerize.pyqtgraphCore.opengl.items', 'mesmerize.pyqtgraphCore.console',
              'mesmerize.pyqtgraphCore.pixmaps', 'mesmerize.pyqtgraphCore.widgets', 'mesmerize.pyqtgraphCore.dockarea',
              'mesmerize.pyqtgraphCore.exporters', 'mesmerize.pyqtgraphCore.exporters.tests',
              'mesmerize.pyqtgraphCore.flowchart', 'mesmerize.pyqtgraphCore.flowchart.library',
              'mesmerize.pyqtgraphCore.imageview', 'mesmerize.pyqtgraphCore.metaarray',
              'mesmerize.pyqtgraphCore.multiprocess', 'mesmerize.pyqtgraphCore.GraphicsScene',
              'mesmerize.pyqtgraphCore.graphicsItems', 'mesmerize.pyqtgraphCore.graphicsItems.ViewBox',
              'mesmerize.pyqtgraphCore.graphicsItems.PlotItem', 'mesmerize.pyqtgraphCore.parametertree',
              'mesmerize.project_manager', 'mesmerize.project_manager.project_browser'],
    entry_points = {'console_scripts': ['mesmerize=mesmerize.main']},
    url='https://kushalkolar.github.io/MESmerize/',
    license='GNU General Public License v3.0',
    author='Kushal Kolar, Daniel Dondorp',
    author_email='kushalkolar@gmail.com',
    description='Calcium imaging analysis platform'
)
