name: mesmerize
version: 0.1.0
summary: Platform for Calcium Imaging analysis
description: >
  Calcium imaging anlaysis platform

confinement: devmode

# When snapcraft performs the build it will try to build the wheels for all pip requirements and try to perform the mesmerize setup.py before those dependencies are actually installed. To workaround this the setup.py catches the imports of the Cython dependencies to allow snap to continue the build. Therefore by having performing the <setup> part before the <mesmerize> pip will build and install all dependencies, and when snapcraft tries to build the <mesmerize> part it will go through the same seutp.py but this time it can actually build the Cython extensions since Cython was installed in the <setup> step.
parts:
  setup:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    # Cython is required for setup.py, python-dateutils is required by pandas and for whatever reason doesn't get installed automatically
    python-packages: [Cython, python-dateutil]
  mesmerize:
    after: [setup]
    plugin: python
    requirements: requirements.txt
    python-version: python3
    source: .
    build-packages:
      - python3
      - python3-tk
      - python3-pyqt5
      - gcc
      - gfortran
      - libblas3
      - liblapack3
      - libopenblas-dev
      - liblapack-dev
      - cython3

    stage-packages:
      - python3
      - python3-tk
      - python3-pyqt5
      - libc-bin
      - locales
      - cython3
      - qtwayland5

apps:
  mesmerize:
    command: desktop-launch $SNAP/bin/mesmerize
    environment:
        # To work on Fedora
        DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - opengl

