# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './system_config.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(663, 531)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxCores = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxCores.sizePolicy().hasHeightForWidth())
        self.spinBoxCores.setSizePolicy(sizePolicy)
        self.spinBoxCores.setMinimum(1)
        self.spinBoxCores.setMaximum(999)
        self.spinBoxCores.setObjectName("spinBoxCores")
        self.horizontalLayout.addWidget(self.spinBoxCores)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBoxUseCUDA = QtWidgets.QCheckBox(Form)
        self.checkBoxUseCUDA.setObjectName("checkBoxUseCUDA")
        self.horizontalLayout_6.addWidget(self.checkBoxUseCUDA)
        self.pushButtonCUDAError = QtWidgets.QPushButton(Form)
        self.pushButtonCUDAError.setObjectName("pushButtonCUDAError")
        self.horizontalLayout_6.addWidget(self.pushButtonCUDAError)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditCaimanPath = QtWidgets.QLineEdit(Form)
        self.lineEditCaimanPath.setReadOnly(True)
        self.lineEditCaimanPath.setObjectName("lineEditCaimanPath")
        self.horizontalLayout_2.addWidget(self.lineEditCaimanPath)
        self.btnCaimanPath = QtWidgets.QPushButton(Form)
        self.btnCaimanPath.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnCaimanPath.setObjectName("btnCaimanPath")
        self.horizontalLayout_2.addWidget(self.btnCaimanPath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.radioButtonVirtualEnv = QtWidgets.QRadioButton(self.widget)
        self.radioButtonVirtualEnv.setObjectName("radioButtonVirtualEnv")
        self.horizontalLayout_4.addWidget(self.radioButtonVirtualEnv)
        self.radioButtonAnaconda = QtWidgets.QRadioButton(self.widget)
        self.radioButtonAnaconda.setObjectName("radioButtonAnaconda")
        self.horizontalLayout_4.addWidget(self.radioButtonAnaconda)
        spacerItem1 = QtWidgets.QSpacerItem(204, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditEnvPath = QtWidgets.QLineEdit(Form)
        self.lineEditEnvPath.setReadOnly(True)
        self.lineEditEnvPath.setObjectName("lineEditEnvPath")
        self.horizontalLayout_3.addWidget(self.lineEditEnvPath)
        self.btnEnvPath = QtWidgets.QPushButton(Form)
        self.btnEnvPath.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnEnvPath.setObjectName("btnEnvPath")
        self.horizontalLayout_3.addWidget(self.btnEnvPath)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.plainTextEditEnvironmentVariables = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEditEnvironmentVariables.sizePolicy().hasHeightForWidth())
        self.plainTextEditEnvironmentVariables.setSizePolicy(sizePolicy)
        self.plainTextEditEnvironmentVariables.setPlainText("")
        self.plainTextEditEnvironmentVariables.setObjectName("plainTextEditEnvironmentVariables")
        self.verticalLayout.addWidget(self.plainTextEditEnvironmentVariables)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.plainTextEditOtherCommands = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plainTextEditOtherCommands.sizePolicy().hasHeightForWidth())
        self.plainTextEditOtherCommands.setSizePolicy(sizePolicy)
        self.plainTextEditOtherCommands.setPlainText("")
        self.plainTextEditOtherCommands.setObjectName("plainTextEditOtherCommands")
        self.verticalLayout.addWidget(self.plainTextEditOtherCommands)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnReloadConfigFile = QtWidgets.QPushButton(Form)
        self.btnReloadConfigFile.setObjectName("btnReloadConfigFile")
        self.horizontalLayout_5.addWidget(self.btnReloadConfigFile)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btnClose = QtWidgets.QPushButton(Form)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_5.addWidget(self.btnClose)
        self.btnApply = QtWidgets.QPushButton(Form)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout_5.addWidget(self.btnApply)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.spinBoxCores, self.lineEditCaimanPath)
        Form.setTabOrder(self.lineEditCaimanPath, self.btnCaimanPath)
        Form.setTabOrder(self.btnCaimanPath, self.lineEditEnvPath)
        Form.setTabOrder(self.lineEditEnvPath, self.btnEnvPath)
        Form.setTabOrder(self.btnEnvPath, self.btnReloadConfigFile)
        Form.setTabOrder(self.btnReloadConfigFile, self.btnClose)
        Form.setTabOrder(self.btnClose, self.btnApply)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Maximum number of cores to use:"))
        self.checkBoxUseCUDA.setText(_translate("Form", "Use CUDA cores when possible"))
        self.pushButtonCUDAError.setText(_translate("Form", "Click to view specific error"))
        self.label_2.setText(_translate("Form", "CaImAn directory path: "))
        self.btnCaimanPath.setText(_translate("Form", "..."))
        self.label_4.setText(_translate("Form", "Environment type:"))
        self.radioButtonVirtualEnv.setText(_translate("Form", "P&ython Virtual Environment"))
        self.radioButtonAnaconda.setText(_translate("Form", "Ananconda&3"))
        self.label_3.setText(_translate("Form", "Environment path: "))
        self.btnEnvPath.setText(_translate("Form", "..."))
        self.label_5.setText(_translate("Form", "Environment variables, one per line"))
        self.label_7.setText(_translate("Form", "Other commands to run before lauching batch items"))
        self.label_6.setText(_translate("Form", "Environment variables, one per line"))
        self.btnReloadConfigFile.setText(_translate("Form", "Reload Config File"))
        self.btnClose.setText(_translate("Form", "Close"))
        self.btnApply.setText(_translate("Form", "Apply"))

