# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './template.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1038, 533)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBoxControls = QtWidgets.QGroupBox(Form)
        self.groupBoxControls.setObjectName("groupBoxControls")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxControls)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxControls)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBoxDataColumn = QtWidgets.QComboBox(self.groupBoxControls)
        self.comboBoxDataColumn.setObjectName("comboBoxDataColumn")
        self.verticalLayout.addWidget(self.comboBoxDataColumn)
        self.pushButtonStart = QtWidgets.QPushButton(self.groupBoxControls)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.verticalLayout.addWidget(self.pushButtonStart)
        self.progressBar = QtWidgets.QProgressBar(self.groupBoxControls)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.label_2 = QtWidgets.QLabel(self.groupBoxControls)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.widget = QtWidgets.QWidget(self.groupBoxControls)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonSqrtResiduals = QtWidgets.QRadioButton(self.widget)
        self.radioButtonSqrtResiduals.setChecked(True)
        self.radioButtonSqrtResiduals.setObjectName("radioButtonSqrtResiduals")
        self.verticalLayout_2.addWidget(self.radioButtonSqrtResiduals)
        self.radioButtonRawResiduals = QtWidgets.QRadioButton(self.widget)
        self.radioButtonRawResiduals.setObjectName("radioButtonRawResiduals")
        self.verticalLayout_2.addWidget(self.radioButtonRawResiduals)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.groupBoxControls)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBoxMean = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxMean.setObjectName("checkBoxMean")
        self.verticalLayout_3.addWidget(self.checkBoxMean)
        self.checkBoxD1Mean = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxD1Mean.setEnabled(False)
        self.checkBoxD1Mean.setObjectName("checkBoxD1Mean")
        self.verticalLayout_3.addWidget(self.checkBoxD1Mean)
        self.checkBoxD2Mean = QtWidgets.QCheckBox(self.widget_2)
        self.checkBoxD2Mean.setEnabled(False)
        self.checkBoxD2Mean.setObjectName("checkBoxD2Mean")
        self.verticalLayout_3.addWidget(self.checkBoxD2Mean)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBoxControls)
        self.groupBoxPlot = QtWidgets.QGroupBox(Form)
        self.groupBoxPlot.setObjectName("groupBoxPlot")
        self.horizontalLayout.addWidget(self.groupBoxPlot)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 7)

        self.retranslateUi(Form)
        self.checkBoxMean.toggled['bool'].connect(self.checkBoxD1Mean.setEnabled)
        self.checkBoxMean.toggled['bool'].connect(self.checkBoxD2Mean.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxControls.setTitle(_translate("Form", "Controls"))
        self.label.setText(_translate("Form", "Data column"))
        self.pushButtonStart.setText(_translate("Form", "Start"))
        self.label_2.setText(_translate("Form", "Plot options:"))
        self.radioButtonSqrtResiduals.setToolTip(_translate("Form", "Plot the sqaure root of the sum of sqaured differences"))
        self.radioButtonSqrtResiduals.setText(_translate("Form", "sqrt of residuals"))
        self.radioButtonRawResiduals.setToolTip(_translate("Form", "Plot the sum of sqaured differences"))
        self.radioButtonRawResiduals.setText(_translate("Form", "raw residuals"))
        self.checkBoxMean.setToolTip(_translate("Form", "Plot just the mean without confidence intervals"))
        self.checkBoxMean.setText(_translate("Form", "mean"))
        self.checkBoxD1Mean.setToolTip(_translate("Form", "Plot the first derivative of the mean"))
        self.checkBoxD1Mean.setText(_translate("Form", "D1 mean"))
        self.checkBoxD2Mean.setToolTip(_translate("Form", "Plot the second derivative of the mean"))
        self.checkBoxD2Mean.setText(_translate("Form", "D2 mean"))
        self.groupBoxPlot.setTitle(_translate("Form", "Plot"))

