# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matplotlibformatter.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 558)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_xylabels = QtWidgets.QWidget()
        self.tab_xylabels.setObjectName("tab_xylabels")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_xylabels)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.tab_xylabels)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_xylabels)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.listWidget_xlabels_orig = QtWidgets.QListWidget(self.tab_xylabels)
        self.listWidget_xlabels_orig.setObjectName("listWidget_xlabels_orig")
        self.gridLayout_5.addWidget(self.listWidget_xlabels_orig, 1, 0, 1, 1)
        self.listWidget_xlabels_edit = QtWidgets.QListWidget(self.tab_xylabels)
        self.listWidget_xlabels_edit.setObjectName("listWidget_xlabels_edit")
        self.gridLayout_5.addWidget(self.listWidget_xlabels_edit, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_xylabels)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_xylabels)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 1, 1, 1)
        self.listWidget_ylabels_orig = QtWidgets.QListWidget(self.tab_xylabels)
        self.listWidget_ylabels_orig.setObjectName("listWidget_ylabels_orig")
        self.gridLayout_5.addWidget(self.listWidget_ylabels_orig, 3, 0, 1, 1)
        self.listWidget_ylabels_edit = QtWidgets.QListWidget(self.tab_xylabels)
        self.listWidget_ylabels_edit.setObjectName("listWidget_ylabels_edit")
        self.gridLayout_5.addWidget(self.listWidget_ylabels_edit, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_xylabels, "")
        self.tab_titles = QtWidgets.QWidget()
        self.tab_titles.setObjectName("tab_titles")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_titles)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tab_titles)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_titles)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        self.listWidget_plottitles_orig = QtWidgets.QListWidget(self.tab_titles)
        self.listWidget_plottitles_orig.setObjectName("listWidget_plottitles_orig")
        self.gridLayout_4.addWidget(self.listWidget_plottitles_orig, 1, 0, 1, 1)
        self.listWidget_plottitles_edit = QtWidgets.QListWidget(self.tab_titles)
        self.listWidget_plottitles_edit.setObjectName("listWidget_plottitles_edit")
        self.gridLayout_4.addWidget(self.listWidget_plottitles_edit, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_titles, "")
        self.tab_ticks = QtWidgets.QWidget()
        self.tab_ticks.setObjectName("tab_ticks")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_ticks)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.tab_ticks)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_ticks)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.listWidget_xticklabels_orig = QtWidgets.QListWidget(self.tab_ticks)
        self.listWidget_xticklabels_orig.setObjectName("listWidget_xticklabels_orig")
        self.gridLayout.addWidget(self.listWidget_xticklabels_orig, 1, 0, 1, 1)
        self.listWidget_xticklabels_edit = QtWidgets.QListWidget(self.tab_ticks)
        self.listWidget_xticklabels_edit.setObjectName("listWidget_xticklabels_edit")
        self.gridLayout.addWidget(self.listWidget_xticklabels_edit, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_ticks)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_ticks)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 1, 1, 1)
        self.listWidget_yticklabels_orig = QtWidgets.QListWidget(self.tab_ticks)
        self.listWidget_yticklabels_orig.setObjectName("listWidget_yticklabels_orig")
        self.gridLayout.addWidget(self.listWidget_yticklabels_orig, 3, 0, 1, 1)
        self.listWidget_yticklabels_edit = QtWidgets.QListWidget(self.tab_ticks)
        self.listWidget_yticklabels_edit.setObjectName("listWidget_yticklabels_edit")
        self.gridLayout.addWidget(self.listWidget_yticklabels_edit, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_ticks, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.pushButton_Apply = QtWidgets.QPushButton(Form)
        self.pushButton_Apply.setObjectName("pushButton_Apply")
        self.gridLayout_2.addWidget(self.pushButton_Apply, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.pushButton_xylabelfont = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_xylabelfont.setObjectName("pushButton_xylabelfont")
        self.gridLayout_3.addWidget(self.pushButton_xylabelfont, 2, 1, 1, 1)
        self.label_currentxylabelfont = QtWidgets.QLabel(self.groupBox)
        self.label_currentxylabelfont.setObjectName("label_currentxylabelfont")
        self.gridLayout_3.addWidget(self.label_currentxylabelfont, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Original X-label "))
        self.label_4.setText(_translate("Form", "User-defined X-label"))
        self.label_5.setText(_translate("Form", "Original Y-label"))
        self.label_6.setText(_translate("Form", "User-defined Y-label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_xylabels), _translate("Form", "XY Labels"))
        self.label_9.setText(_translate("Form", "Original"))
        self.label_8.setText(_translate("Form", "User-defined"))
        self.listWidget_plottitles_edit.setToolTip(_translate("Form", "<html><head/><body><p>double-click to edit.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_titles), _translate("Form", "Titles"))
        self.label_13.setText(_translate("Form", "Original X-label "))
        self.label_10.setText(_translate("Form", "User-defined X-label"))
        self.label_12.setText(_translate("Form", "Original Y-label"))
        self.label_11.setText(_translate("Form", "User-defined Y-label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ticks), _translate("Form", "Ticks"))
        self.pushButton_Apply.setText(_translate("Form", "Apply Changes"))
        self.groupBox.setTitle(_translate("Form", "XY font style"))
        self.label_7.setText(_translate("Form", "fontsize"))
        self.pushButton_xylabelfont.setText(_translate("Form", "font"))
        self.label_currentxylabelfont.setText(_translate("Form", "Current Font: "))


