# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batch_manager.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1110, 645)
        DockWidget.setFloating(True)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_3 = QtWidgets.QSplitter(self.dockWidgetContents)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listwBatch = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwBatch.sizePolicy().hasHeightForWidth())
        self.listwBatch.setSizePolicy(sizePolicy)
        self.listwBatch.setObjectName("listwBatch")
        self.verticalLayout.addWidget(self.listwBatch)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(48, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 2, 1)
        self.btnStart = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setMinimumSize(QtCore.QSize(55, 0))
        self.btnStart.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btnStart.setBaseSize(QtCore.QSize(60, 0))
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_2.addWidget(self.btnStart, 0, 1, 1, 1)
        self.btnStartAtSelection = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartAtSelection.sizePolicy().hasHeightForWidth())
        self.btnStartAtSelection.setSizePolicy(sizePolicy)
        self.btnStartAtSelection.setMinimumSize(QtCore.QSize(125, 0))
        self.btnStartAtSelection.setMaximumSize(QtCore.QSize(125, 16777215))
        self.btnStartAtSelection.setBaseSize(QtCore.QSize(60, 0))
        self.btnStartAtSelection.setObjectName("btnStartAtSelection")
        self.gridLayout_2.addWidget(self.btnStartAtSelection, 0, 2, 1, 2)
        self.btnDelete = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setMinimumSize(QtCore.QSize(105, 0))
        self.btnDelete.setMaximumSize(QtCore.QSize(105, 16777215))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_2.addWidget(self.btnDelete, 0, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(48, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 6, 2, 1)
        self.btnAbort = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAbort.sizePolicy().hasHeightForWidth())
        self.btnAbort.setSizePolicy(sizePolicy)
        self.btnAbort.setMinimumSize(QtCore.QSize(55, 0))
        self.btnAbort.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btnAbort.setBaseSize(QtCore.QSize(60, 0))
        self.btnAbort.setObjectName("btnAbort")
        self.gridLayout_2.addWidget(self.btnAbort, 1, 1, 1, 1)
        self.btnNew = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNew.sizePolicy().hasHeightForWidth())
        self.btnNew.setSizePolicy(sizePolicy)
        self.btnNew.setMinimumSize(QtCore.QSize(75, 0))
        self.btnNew.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnNew.setBaseSize(QtCore.QSize(60, 0))
        self.btnNew.setObjectName("btnNew")
        self.gridLayout_2.addWidget(self.btnNew, 1, 2, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpen.sizePolicy().hasHeightForWidth())
        self.btnOpen.setSizePolicy(sizePolicy)
        self.btnOpen.setMinimumSize(QtCore.QSize(75, 0))
        self.btnOpen.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnOpen.setBaseSize(QtCore.QSize(60, 0))
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout_2.addWidget(self.btnOpen, 1, 3, 1, 2)
        self.btnViewInput = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnViewInput.sizePolicy().hasHeightForWidth())
        self.btnViewInput.setSizePolicy(sizePolicy)
        self.btnViewInput.setMinimumSize(QtCore.QSize(70, 0))
        self.btnViewInput.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btnViewInput.setBaseSize(QtCore.QSize(70, 0))
        self.btnViewInput.setObjectName("btnViewInput")
        self.gridLayout_2.addWidget(self.btnViewInput, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 407, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowserItemInfo = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowserItemInfo.setObjectName("textBrowserItemInfo")
        self.gridLayout.addWidget(self.textBrowserItemInfo, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.scrollAreaStdOut = QtWidgets.QScrollArea(self.splitter_2)
        self.scrollAreaStdOut.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollAreaStdOut.sizePolicy().hasHeightForWidth())
        self.scrollAreaStdOut.setSizePolicy(sizePolicy)
        self.scrollAreaStdOut.setWidgetResizable(True)
        self.scrollAreaStdOut.setObjectName("scrollAreaStdOut")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 677, 300))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowserStdOut = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_4)
        self.textBrowserStdOut.setObjectName("textBrowserStdOut")
        self.gridLayout_3.addWidget(self.textBrowserStdOut, 0, 0, 1, 1)
        self.scrollAreaStdOut.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollAreaOutputInfo = QtWidgets.QScrollArea(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollAreaOutputInfo.sizePolicy().hasHeightForWidth())
        self.scrollAreaOutputInfo.setSizePolicy(sizePolicy)
        self.scrollAreaOutputInfo.setWidgetResizable(True)
        self.scrollAreaOutputInfo.setObjectName("scrollAreaOutputInfo")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 677, 300))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowserOutputInfo = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_6)
        self.textBrowserOutputInfo.setObjectName("textBrowserOutputInfo")
        self.gridLayout_8.addWidget(self.textBrowserOutputInfo, 0, 0, 1, 1)
        self.scrollAreaOutputInfo.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_4.addWidget(self.splitter_3, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.listwBatch, self.btnStart)
        DockWidget.setTabOrder(self.btnStart, self.scrollArea)
        DockWidget.setTabOrder(self.scrollArea, self.scrollAreaStdOut)
        DockWidget.setTabOrder(self.scrollAreaStdOut, self.scrollAreaOutputInfo)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Batch Manager"))
        self.btnStart.setText(_translate("DockWidget", "Start"))
        self.btnStartAtSelection.setText(_translate("DockWidget", "Start at selection"))
        self.btnDelete.setText(_translate("DockWidget", "Delete selection"))
        self.btnAbort.setText(_translate("DockWidget", "Abort"))
        self.btnNew.setText(_translate("DockWidget", "New Batch"))
        self.btnOpen.setText(_translate("DockWidget", "Open Batch"))
        self.btnViewInput.setText(_translate("DockWidget", "View Input"))
        self.textBrowserItemInfo.setHtml(_translate("DockWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

