# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './batch_manager.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(1206, 653)
        DockWidget.setFloating(True)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnDelete = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDelete.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_2.addWidget(self.btnDelete, 1, 5, 1, 1)
        self.listwBatch = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwBatch.sizePolicy().hasHeightForWidth())
        self.listwBatch.setSizePolicy(sizePolicy)
        self.listwBatch.setObjectName("listwBatch")
        self.gridLayout_2.addWidget(self.listwBatch, 0, 0, 1, 8)
        self.btnNew = QtWidgets.QPushButton(self.layoutWidget)
        self.btnNew.setMaximumSize(QtCore.QSize(65, 16777215))
        self.btnNew.setBaseSize(QtCore.QSize(60, 0))
        self.btnNew.setObjectName("btnNew")
        self.gridLayout_2.addWidget(self.btnNew, 1, 3, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOpen.setMaximumSize(QtCore.QSize(65, 16777215))
        self.btnOpen.setBaseSize(QtCore.QSize(60, 0))
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout_2.addWidget(self.btnOpen, 1, 4, 1, 1)
        self.btnStart = QtWidgets.QPushButton(self.layoutWidget)
        self.btnStart.setMaximumSize(QtCore.QSize(65, 16777215))
        self.btnStart.setBaseSize(QtCore.QSize(60, 0))
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_2.addWidget(self.btnStart, 1, 1, 1, 1)
        self.btnAbort = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAbort.setMaximumSize(QtCore.QSize(65, 16777215))
        self.btnAbort.setBaseSize(QtCore.QSize(60, 0))
        self.btnAbort.setObjectName("btnAbort")
        self.gridLayout_2.addWidget(self.btnAbort, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 7, 1, 1)
        self.btnViewInput = QtWidgets.QPushButton(self.layoutWidget)
        self.btnViewInput.setMaximumSize(QtCore.QSize(65, 16777215))
        self.btnViewInput.setBaseSize(QtCore.QSize(60, 0))
        self.btnViewInput.setObjectName("btnViewInput")
        self.gridLayout_2.addWidget(self.btnViewInput, 1, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 547, 343))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelMeta_info = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelMeta_info.setText("")
        self.labelMeta_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelMeta_info.setObjectName("labelMeta_info")
        self.gridLayout.addWidget(self.labelMeta_info, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_11.addWidget(self.splitter, 0, 0, 2, 1)
        self.scrollAreaStdOut = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollAreaStdOut.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollAreaStdOut.sizePolicy().hasHeightForWidth())
        self.scrollAreaStdOut.setSizePolicy(sizePolicy)
        self.scrollAreaStdOut.setWidgetResizable(True)
        self.scrollAreaStdOut.setObjectName("scrollAreaStdOut")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 631, 303))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelStdOut = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.labelStdOut.setText("")
        self.labelStdOut.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelStdOut.setWordWrap(True)
        self.labelStdOut.setObjectName("labelStdOut")
        self.gridLayout_3.addWidget(self.labelStdOut, 0, 0, 1, 1)
        self.scrollAreaStdOut.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_11.addWidget(self.scrollAreaStdOut, 0, 1, 1, 1)
        self.scrollAreaOutputInfo = QtWidgets.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollAreaOutputInfo.sizePolicy().hasHeightForWidth())
        self.scrollAreaOutputInfo.setSizePolicy(sizePolicy)
        self.scrollAreaOutputInfo.setWidgetResizable(True)
        self.scrollAreaOutputInfo.setObjectName("scrollAreaOutputInfo")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 631, 303))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.labelOutputInfo = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.labelOutputInfo.setText("")
        self.labelOutputInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelOutputInfo.setObjectName("labelOutputInfo")
        self.gridLayout_8.addWidget(self.labelOutputInfo, 0, 0, 1, 1)
        self.scrollAreaOutputInfo.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_11.addWidget(self.scrollAreaOutputInfo, 1, 1, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)
        DockWidget.setTabOrder(self.listwBatch, self.btnStart)
        DockWidget.setTabOrder(self.btnStart, self.btnAbort)
        DockWidget.setTabOrder(self.btnAbort, self.btnNew)
        DockWidget.setTabOrder(self.btnNew, self.btnOpen)
        DockWidget.setTabOrder(self.btnOpen, self.btnDelete)
        DockWidget.setTabOrder(self.btnDelete, self.btnViewInput)
        DockWidget.setTabOrder(self.btnViewInput, self.scrollArea)
        DockWidget.setTabOrder(self.scrollArea, self.scrollAreaStdOut)
        DockWidget.setTabOrder(self.scrollAreaStdOut, self.scrollAreaOutputInfo)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Batch Manager"))
        self.btnDelete.setText(_translate("DockWidget", "Delete selection"))
        self.btnNew.setText(_translate("DockWidget", "New"))
        self.btnOpen.setText(_translate("DockWidget", "Open"))
        self.btnStart.setText(_translate("DockWidget", "Start"))
        self.btnAbort.setText(_translate("DockWidget", "Abort"))
        self.btnViewInput.setText(_translate("DockWidget", "View Input"))

