# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cnmfe_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.setWindowModality(QtCore.Qt.NonModal)
        DockWidget.resize(486, 771)
        DockWidget.setFloating(True)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.comboBoxInputCorrPNR = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBoxInputCorrPNR.setObjectName("comboBoxInputCorrPNR")
        self.comboBoxInputCorrPNR.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxInputCorrPNR)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxGSig = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxGSig.setObjectName("spinBoxGSig")
        self.horizontalLayout.addWidget(self.spinBoxGSig)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBoxGSize = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxGSize.setObjectName("spinBoxGSize")
        self.horizontalLayout_2.addWidget(self.spinBoxGSize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.btnAddToBatchCorrPNR = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnAddToBatchCorrPNR.setObjectName("btnAddToBatchCorrPNR")
        self.horizontalLayout_3.addWidget(self.btnAddToBatchCorrPNR)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 9, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBoxCNMFE = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBoxCNMFE.setObjectName("comboBoxCNMFE")
        self.comboBoxCNMFE.addItem("")
        self.comboBoxCNMFE.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxCNMFE)
        self.gridLayout.addLayout(self.horizontalLayout_5, 11, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 13, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.doubleSpinBoxMinCorr = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxMinCorr.setObjectName("doubleSpinBoxMinCorr")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxMinCorr)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_6, 14, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 15, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.spinBoxMinPNR = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxMinPNR.setObjectName("spinBoxMinPNR")
        self.horizontalLayout_7.addWidget(self.spinBoxMinPNR)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_7, 16, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 17, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.spinBoxMinSNR = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxMinSNR.setObjectName("spinBoxMinSNR")
        self.horizontalLayout_8.addWidget(self.spinBoxMinSNR)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_8, 18, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 19, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.doubleSpinBoxRValuesMin = QtWidgets.QDoubleSpinBox(self.dockWidgetContents)
        self.doubleSpinBoxRValuesMin.setObjectName("doubleSpinBoxRValuesMin")
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxRValuesMin)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_9, 20, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 21, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.spinBoxDecayTime = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.spinBoxDecayTime.setObjectName("spinBoxDecayTime")
        self.horizontalLayout_10.addWidget(self.spinBoxDecayTime)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_10, 22, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.lineEdName = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdName.setObjectName("lineEdName")
        self.horizontalLayout_11.addWidget(self.lineEdName)
        self.btnAddToBatchCNMFE = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnAddToBatchCNMFE.setObjectName("btnAddToBatchCNMFE")
        self.horizontalLayout_11.addWidget(self.btnAddToBatchCNMFE)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_11, 23, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btnExport = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_12.addWidget(self.btnExport)
        self.btnImport = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnImport.setObjectName("btnImport")
        self.horizontalLayout_12.addWidget(self.btnImport)
        self.gridLayout.addLayout(self.horizontalLayout_12, 24, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_21.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.radioButtonCNMFEInputWriteNow = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButtonCNMFEInputWriteNow.setObjectName("radioButtonCNMFEInputWriteNow")
        self.horizontalLayout_13.addWidget(self.radioButtonCNMFEInputWriteNow)
        self.line_3 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_13.addWidget(self.line_3)
        self.radioButtonCNMFEInputWriteRuntime = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButtonCNMFEInputWriteRuntime.setObjectName("radioButtonCNMFEInputWriteRuntime")
        self.horizontalLayout_13.addWidget(self.radioButtonCNMFEInputWriteRuntime)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout_13, 12, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_22 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_22.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.radioButtonInputWriteCorrPNRNow = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButtonInputWriteCorrPNRNow.setObjectName("radioButtonInputWriteCorrPNRNow")
        self.horizontalLayout_14.addWidget(self.radioButtonInputWriteCorrPNRNow)
        self.line_4 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_14.addWidget(self.line_4)
        self.radioButtonInputWriteCorrPNRRuntime = QtWidgets.QRadioButton(self.dockWidgetContents)
        self.radioButtonInputWriteCorrPNRRuntime.setObjectName("radioButtonInputWriteCorrPNRRuntime")
        self.horizontalLayout_14.addWidget(self.radioButtonInputWriteCorrPNRRuntime)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "CNMF-E"))
        self.label_19.setText(_translate("DockWidget", "Input:"))
        self.comboBoxInputCorrPNR.setItemText(0, _translate("DockWidget", "Current Work Environment"))
        self.label_5.setToolTip(_translate("DockWidget", "Compute some summary images (correlation and peak to noise ratio)"))
        self.label_5.setText(_translate("DockWidget", "Inspect Correlation PNR"))
        self.label_2.setText(_translate("DockWidget", "gaussian width of a 2D gaussian kernel, which approximates a neuron"))
        self.label.setText(_translate("DockWidget", "gSig:"))
        self.label_4.setText(_translate("DockWidget", "average diameter of a neuron"))
        self.label_3.setText(_translate("DockWidget", "gSize:"))
        self.label_9.setText(_translate("DockWidget", "Stop here:"))
        self.btnAddToBatchCorrPNR.setText(_translate("DockWidget", "Add to batch"))
        self.label_20.setText(_translate("DockWidget", "CNMF-E"))
        self.label_6.setText(_translate("DockWidget", "Input:"))
        self.comboBoxCNMFE.setItemText(0, _translate("DockWidget", "Continue from above"))
        self.comboBoxCNMFE.setItemText(1, _translate("DockWidget", "Current Work Environment"))
        self.label_7.setText(_translate("DockWidget", "Minimum correlation of peak (from correlation image)"))
        self.label_8.setText(_translate("DockWidget", "min_corr:"))
        self.label_11.setText(_translate("DockWidget", "Minimum peak to noise ratio"))
        self.label_10.setText(_translate("DockWidget", "min_pnr:"))
        self.label_13.setText(_translate("DockWidget", "Adaptive way to set threshold on the transient size"))
        self.label_12.setText(_translate("DockWidget", "min_SNR:"))
        self.label_14.setText(_translate("DockWidget", "Threshold on space consistency \n"
"If lower more components will be accepted, potentially with worse quality"))
        self.label_15.setText(_translate("DockWidget", "r_values_min:"))
        self.label_17.setText(_translate("DockWidget", "Average decay time of transients"))
        self.label_16.setText(_translate("DockWidget", "decay_time:"))
        self.label_18.setText(_translate("DockWidget", "Perform CNMF-E:"))
        self.lineEdName.setPlaceholderText(_translate("DockWidget", "Enter name"))
        self.btnAddToBatchCNMFE.setText(_translate("DockWidget", "Add to batch"))
        self.btnExport.setText(_translate("DockWidget", "Export Parameters"))
        self.btnImport.setText(_translate("DockWidget", "Import Parameters"))
        self.label_21.setText(_translate("DockWidget", "Write input to disk:"))
        self.radioButtonCNMFEInputWriteNow.setText(_translate("DockWidget", "Now"))
        self.radioButtonCNMFEInputWriteRuntime.setText(_translate("DockWidget", "At batch run-time"))
        self.label_22.setText(_translate("DockWidget", "Write input to disk:"))
        self.radioButtonInputWriteCorrPNRNow.setText(_translate("DockWidget", "Now"))
        self.radioButtonInputWriteCorrPNRRuntime.setText(_translate("DockWidget", "At batch run-time"))

