# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './standard_tools_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(332, 127)
        DockWidget.setFloating(True)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnCrop = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnCrop.sizePolicy().hasHeightForWidth())
        self.btnCrop.setSizePolicy(sizePolicy)
        self.btnCrop.setMinimumSize(QtCore.QSize(100, 25))
        self.btnCrop.setMaximumSize(QtCore.QSize(100, 25))
        self.btnCrop.setIconSize(QtCore.QSize(16, 16))
        self.btnCrop.setCheckable(True)
        self.btnCrop.setObjectName("btnCrop")
        self.gridLayout.addWidget(self.btnCrop, 0, 0, 1, 1)
        self.btnResizeImgseq = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResizeImgseq.sizePolicy().hasHeightForWidth())
        self.btnResizeImgseq.setSizePolicy(sizePolicy)
        self.btnResizeImgseq.setMinimumSize(QtCore.QSize(100, 25))
        self.btnResizeImgseq.setMaximumSize(QtCore.QSize(100, 25))
        self.btnResizeImgseq.setIconSize(QtCore.QSize(16, 16))
        self.btnResizeImgseq.setObjectName("btnResizeImgseq")
        self.gridLayout.addWidget(self.btnResizeImgseq, 0, 1, 1, 1)
        self.btnImportSMap = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnImportSMap.sizePolicy().hasHeightForWidth())
        self.btnImportSMap.setSizePolicy(sizePolicy)
        self.btnImportSMap.setMinimumSize(QtCore.QSize(100, 25))
        self.btnImportSMap.setMaximumSize(QtCore.QSize(100, 25))
        self.btnImportSMap.setIconSize(QtCore.QSize(16, 16))
        self.btnImportSMap.setCheckable(True)
        self.btnImportSMap.setObjectName("btnImportSMap")
        self.gridLayout.addWidget(self.btnImportSMap, 0, 2, 1, 1)
        self.btnResetScale = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnResetScale.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResetScale.sizePolicy().hasHeightForWidth())
        self.btnResetScale.setSizePolicy(sizePolicy)
        self.btnResetScale.setMinimumSize(QtCore.QSize(100, 25))
        self.btnResetScale.setMaximumSize(QtCore.QSize(100, 25))
        self.btnResetScale.setObjectName("btnResetScale")
        self.gridLayout.addWidget(self.btnResetScale, 1, 0, 1, 1)
        self.btnEditMetaData = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnEditMetaData.sizePolicy().hasHeightForWidth())
        self.btnEditMetaData.setSizePolicy(sizePolicy)
        self.btnEditMetaData.setMinimumSize(QtCore.QSize(100, 25))
        self.btnEditMetaData.setMaximumSize(QtCore.QSize(100, 25))
        self.btnEditMetaData.setIconSize(QtCore.QSize(16, 16))
        self.btnEditMetaData.setObjectName("btnEditMetaData")
        self.gridLayout.addWidget(self.btnEditMetaData, 1, 1, 1, 1)
        self.btnChangeSMap = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnChangeSMap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnChangeSMap.sizePolicy().hasHeightForWidth())
        self.btnChangeSMap.setSizePolicy(sizePolicy)
        self.btnChangeSMap.setMinimumSize(QtCore.QSize(100, 25))
        self.btnChangeSMap.setMaximumSize(QtCore.QSize(100, 25))
        self.btnChangeSMap.setObjectName("btnChangeSMap")
        self.gridLayout.addWidget(self.btnChangeSMap, 1, 2, 1, 1)
        self.btnPlot = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnPlot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnPlot.sizePolicy().hasHeightForWidth())
        self.btnPlot.setSizePolicy(sizePolicy)
        self.btnPlot.setMinimumSize(QtCore.QSize(100, 25))
        self.btnPlot.setMaximumSize(QtCore.QSize(100, 25))
        self.btnPlot.setIconSize(QtCore.QSize(16, 16))
        self.btnPlot.setCheckable(True)
        self.btnPlot.setChecked(True)
        self.btnPlot.setObjectName("btnPlot")
        self.gridLayout.addWidget(self.btnPlot, 2, 0, 1, 1)
        self.btnResetSMap = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnResetSMap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResetSMap.sizePolicy().hasHeightForWidth())
        self.btnResetSMap.setSizePolicy(sizePolicy)
        self.btnResetSMap.setMinimumSize(QtCore.QSize(100, 25))
        self.btnResetSMap.setMaximumSize(QtCore.QSize(100, 25))
        self.btnResetSMap.setObjectName("btnResetSMap")
        self.gridLayout.addWidget(self.btnResetSMap, 2, 2, 1, 1)
        self.btnMeasureTool = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnMeasureTool.sizePolicy().hasHeightForWidth())
        self.btnMeasureTool.setSizePolicy(sizePolicy)
        self.btnMeasureTool.setMinimumSize(QtCore.QSize(100, 25))
        self.btnMeasureTool.setMaximumSize(QtCore.QSize(100, 25))
        self.btnMeasureTool.setIconSize(QtCore.QSize(16, 16))
        self.btnMeasureTool.setCheckable(True)
        self.btnMeasureTool.setObjectName("btnMeasureTool")
        self.gridLayout.addWidget(self.btnMeasureTool, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Standard Tools"))
        self.btnCrop.setText(_translate("DockWidget", "Crop"))
        self.btnResizeImgseq.setToolTip(_translate("DockWidget", "Add ROI to the image"))
        self.btnResizeImgseq.setText(_translate("DockWidget", "Resize"))
        self.btnImportSMap.setText(_translate("DockWidget", "Import sMap"))
        self.btnResetScale.setToolTip(_translate("DockWidget", "Reset scale of the image and timeline"))
        self.btnResetScale.setText(_translate("DockWidget", "Reset scale"))
        self.btnEditMetaData.setToolTip(_translate("DockWidget", "Add ROI to the image"))
        self.btnEditMetaData.setText(_translate("DockWidget", "Edit meta-data"))
        self.btnChangeSMap.setToolTip(_translate("DockWidget", "<html><head/><body><p>Change the Stimulus Map.</p></body></html>"))
        self.btnChangeSMap.setText(_translate("DockWidget", "Change sMap"))
        self.btnPlot.setToolTip(_translate("DockWidget", "Add ROI to the image"))
        self.btnPlot.setText(_translate("DockWidget", "Plot"))
        self.btnResetSMap.setToolTip(_translate("DockWidget", "<html><head/><body><p>Reset the Stimulus Map to the one set for this mes file.</p></body></html>"))
        self.btnResetSMap.setText(_translate("DockWidget", "Reset sMap"))
        self.btnMeasureTool.setToolTip(_translate("DockWidget", "Add ROI to the image"))
        self.btnMeasureTool.setText(_translate("DockWidget", "Measure tool"))

