# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './welcome_window_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 10, 897, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNewProj = QtWidgets.QLabel(self.layoutWidget)
        self.labelNewProj.setObjectName("labelNewProj")
        self.verticalLayout.addWidget(self.labelNewProj)
        self.btnNewProject = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewProject.sizePolicy().hasHeightForWidth())
        self.btnNewProject.setSizePolicy(sizePolicy)
        self.btnNewProject.setMinimumSize(QtCore.QSize(131, 118))
        self.btnNewProject.setMaximumSize(QtCore.QSize(131, 118))
        self.btnNewProject.setAutoFillBackground(True)
        self.btnNewProject.setText("")
        self.btnNewProject.setFlat(False)
        self.btnNewProject.setObjectName("btnNewProject")
        self.verticalLayout.addWidget(self.btnNewProject)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayoutProjectBrowser = QtWidgets.QVBoxLayout()
        self.verticalLayoutProjectBrowser.setObjectName("verticalLayoutProjectBrowser")
        self.labelProjectBrowser = QtWidgets.QLabel(self.layoutWidget)
        self.labelProjectBrowser.setObjectName("labelProjectBrowser")
        self.verticalLayoutProjectBrowser.addWidget(self.labelProjectBrowser)
        self.btnProjectBrowser = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProjectBrowser.sizePolicy().hasHeightForWidth())
        self.btnProjectBrowser.setSizePolicy(sizePolicy)
        self.btnProjectBrowser.setMinimumSize(QtCore.QSize(131, 118))
        self.btnProjectBrowser.setMaximumSize(QtCore.QSize(131, 118))
        self.btnProjectBrowser.setAutoFillBackground(True)
        self.btnProjectBrowser.setText("")
        self.btnProjectBrowser.setFlat(False)
        self.btnProjectBrowser.setObjectName("btnProjectBrowser")
        self.verticalLayoutProjectBrowser.addWidget(self.btnProjectBrowser)
        self.horizontalLayout.addLayout(self.verticalLayoutProjectBrowser)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelOpenProject = QtWidgets.QLabel(self.layoutWidget)
        self.labelOpenProject.setObjectName("labelOpenProject")
        self.verticalLayout_2.addWidget(self.labelOpenProject)
        self.btnOpenProject = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenProject.sizePolicy().hasHeightForWidth())
        self.btnOpenProject.setSizePolicy(sizePolicy)
        self.btnOpenProject.setMinimumSize(QtCore.QSize(131, 118))
        self.btnOpenProject.setMaximumSize(QtCore.QSize(131, 118))
        self.btnOpenProject.setAutoFillBackground(True)
        self.btnOpenProject.setText("")
        self.btnOpenProject.setFlat(False)
        self.btnOpenProject.setObjectName("btnOpenProject")
        self.verticalLayout_2.addWidget(self.btnOpenProject)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.labelRecentProjects = QtWidgets.QLabel(self.layoutWidget)
        self.labelRecentProjects.setObjectName("labelRecentProjects")
        self.verticalLayout_14.addWidget(self.labelRecentProjects)
        self.listWidgetRecentProjects = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidgetRecentProjects.setMinimumSize(QtCore.QSize(470, 118))
        self.listWidgetRecentProjects.setMaximumSize(QtCore.QSize(470, 118))
        self.listWidgetRecentProjects.setObjectName("listWidgetRecentProjects")
        self.verticalLayout_14.addWidget(self.listWidgetRecentProjects)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 170, 760, 146))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.btnViewer = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnViewer.sizePolicy().hasHeightForWidth())
        self.btnViewer.setSizePolicy(sizePolicy)
        self.btnViewer.setMinimumSize(QtCore.QSize(131, 118))
        self.btnViewer.setMaximumSize(QtCore.QSize(131, 118))
        self.btnViewer.setAutoFillBackground(True)
        self.btnViewer.setText("")
        self.btnViewer.setFlat(False)
        self.btnViewer.setObjectName("btnViewer")
        self.verticalLayout_4.addWidget(self.btnViewer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayoutViewersRunning = QtWidgets.QVBoxLayout()
        self.verticalLayoutViewersRunning.setObjectName("verticalLayoutViewersRunning")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayoutViewersRunning.addWidget(self.label_9)
        self.horizontalLayout_2.addLayout(self.verticalLayoutViewersRunning)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.btnFlowchart = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFlowchart.sizePolicy().hasHeightForWidth())
        self.btnFlowchart.setSizePolicy(sizePolicy)
        self.btnFlowchart.setMinimumSize(QtCore.QSize(131, 118))
        self.btnFlowchart.setMaximumSize(QtCore.QSize(131, 118))
        self.btnFlowchart.setAutoFillBackground(True)
        self.btnFlowchart.setText("")
        self.btnFlowchart.setFlat(False)
        self.btnFlowchart.setObjectName("btnFlowchart")
        self.verticalLayout_6.addWidget(self.btnFlowchart)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayoutFlowchartRunning = QtWidgets.QVBoxLayout()
        self.verticalLayoutFlowchartRunning.setObjectName("verticalLayoutFlowchartRunning")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayoutFlowchartRunning.addWidget(self.label_10)
        self.horizontalLayout_2.addLayout(self.verticalLayoutFlowchartRunning)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.listWidgetPlots_5 = QtWidgets.QListWidget(self.layoutWidget1)
        self.listWidgetPlots_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetPlots_5.sizePolicy().hasHeightForWidth())
        self.listWidgetPlots_5.setSizePolicy(sizePolicy)
        self.listWidgetPlots_5.setMinimumSize(QtCore.QSize(331, 118))
        self.listWidgetPlots_5.setMaximumSize(QtCore.QSize(241, 118))
        self.listWidgetPlots_5.setObjectName("listWidgetPlots_5")
        self.verticalLayout_13.addWidget(self.listWidgetPlots_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 30))
        self.menubar.setObjectName("menubar")
        self.menuConfiguration = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockConsole = QtWidgets.QDockWidget(MainWindow)
        self.dockConsole.setMinimumSize(QtCore.QSize(68, 250))
        self.dockConsole.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockConsole.setObjectName("dockConsole")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockConsole.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockConsole)
        self.actionProject_Configuration = QtWidgets.QAction(MainWindow)
        self.actionProject_Configuration.setEnabled(False)
        self.actionProject_Configuration.setObjectName("actionProject_Configuration")
        self.actionSystem_Configuration = QtWidgets.QAction(MainWindow)
        self.actionSystem_Configuration.setObjectName("actionSystem_Configuration")
        self.actionShow_all_windows = QtWidgets.QAction(MainWindow)
        self.actionShow_all_windows.setObjectName("actionShow_all_windows")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        self.actionConsole.setCheckable(True)
        self.actionConsole.setObjectName("actionConsole")
        self.actionViewer_linker = QtWidgets.QAction(MainWindow)
        self.actionViewer_linker.setObjectName("actionViewer_linker")
        self.menuConfiguration.addAction(self.actionProject_Configuration)
        self.menuConfiguration.addAction(self.actionSystem_Configuration)
        self.menuView.addAction(self.actionShow_all_windows)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionConsole)
        self.menuTools.addAction(self.actionViewer_linker)
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.actionConsole.toggled['bool'].connect(self.dockConsole.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNewProj.setText(_translate("MainWindow", "New Project"))
        self.labelProjectBrowser.setText(_translate("MainWindow", "Project Browser"))
        self.labelOpenProject.setText(_translate("MainWindow", "Open Project"))
        self.labelRecentProjects.setText(_translate("MainWindow", "Recent Projects"))
        self.label_4.setText(_translate("MainWindow", "Viewer"))
        self.label_9.setText(_translate("MainWindow", "Running"))
        self.label_5.setText(_translate("MainWindow", "Flowchart"))
        self.label_10.setText(_translate("MainWindow", "Running"))
        self.label_13.setText(_translate("MainWindow", "In current project"))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Confi&guration"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuTools.setTitle(_translate("MainWindow", "Too&ls"))
        self.dockConsole.setWindowTitle(_translate("MainWindow", "&Console: Welcome Window"))
        self.actionProject_Configuration.setText(_translate("MainWindow", "&Project Configuration"))
        self.actionSystem_Configuration.setText(_translate("MainWindow", "&System Configuration"))
        self.actionShow_all_windows.setText(_translate("MainWindow", "&Show all windows"))
        self.actionConsole.setText(_translate("MainWindow", "&Console"))
        self.actionViewer_linker.setText(_translate("MainWindow", "&Viewer linker"))

