# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageViewTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1400, 980)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.FileMenusLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.FileMenusLayout.setContentsMargins(0, 0, 0, 0)
        self.FileMenusLayout.setObjectName("FileMenusLayout")
        self.openFileBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.openFileBtn.setObjectName("openFileBtn")
        self.FileMenusLayout.addWidget(self.openFileBtn, 0, 0, 1, 1)
        self.mesfile_label = QtWidgets.QLabel(self.layoutWidget)
        self.mesfile_label.setObjectName("mesfile_label")
        self.FileMenusLayout.addWidget(self.mesfile_label, 1, 0, 1, 1)
        self.imgs_list_label = QtWidgets.QLabel(self.layoutWidget)
        self.imgs_list_label.setObjectName("imgs_list_label")
        self.FileMenusLayout.addWidget(self.imgs_list_label, 1, 1, 1, 1)
        self.mesfile_listw = QtWidgets.QListWidget(self.layoutWidget)
        self.mesfile_listw.setObjectName("mesfile_listw")
        self.FileMenusLayout.addWidget(self.mesfile_listw, 2, 0, 1, 1)
        self.imgs_listw = QtWidgets.QListWidget(self.layoutWidget)
        self.imgs_listw.setObjectName("imgs_listw")
        self.FileMenusLayout.addWidget(self.imgs_listw, 2, 1, 1, 1)
        self.progressBarLabel = QtWidgets.QLabel(self.layoutWidget)
        self.progressBarLabel.setText("")
        self.progressBarLabel.setObjectName("progressBarLabel")
        self.FileMenusLayout.addWidget(self.progressBarLabel, 3, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 600))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.abortBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.abortBtn.setObjectName("abortBtn")
        self.gridLayout.addWidget(self.abortBtn, 0, 2, 1, 1)
        self.histogram = HistogramLUTWidget(self.layoutWidget1)
        self.histogram.setObjectName("histogram")
        self.gridLayout.addWidget(self.histogram, 1, 1, 1, 2)
        self.exportBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.exportBtn.setObjectName("exportBtn")
        self.gridLayout.addWidget(self.exportBtn, 2, 1, 1, 1)
        self.motcor_gui_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.motcor_gui_Btn.setCheckable(True)
        self.motcor_gui_Btn.setObjectName("motcor_gui_Btn")
        self.gridLayout.addWidget(self.motcor_gui_Btn, 2, 2, 1, 1)
        self.add_roi_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_roi_Btn.sizePolicy().hasHeightForWidth())
        self.add_roi_Btn.setSizePolicy(sizePolicy)
        self.add_roi_Btn.setIconSize(QtCore.QSize(16, 16))
        self.add_roi_Btn.setObjectName("add_roi_Btn")
        self.gridLayout.addWidget(self.add_roi_Btn, 3, 1, 1, 1)
        self.liveupdateBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.liveupdateBtn.setObjectName("liveupdateBtn")
        self.gridLayout.addWidget(self.liveupdateBtn, 3, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 2)
        self.load_roi_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.load_roi_Btn.setObjectName("load_roi_Btn")
        self.gridLayout.addWidget(self.load_roi_Btn, 4, 1, 1, 1)
        self.save_roi_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.save_roi_Btn.setObjectName("save_roi_Btn")
        self.gridLayout.addWidget(self.save_roi_Btn, 4, 2, 1, 1)
        self.resetscaleBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.resetscaleBtn.setObjectName("resetscaleBtn")
        self.gridLayout.addWidget(self.resetscaleBtn, 5, 1, 1, 1)
        self.graphicsView = GraphicsView(self.layoutWidget1)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 5, 1)
        self.addtoProjBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.addtoProjBtn.setObjectName("addtoProjBtn")
        self.gridLayout.addWidget(self.addtoProjBtn, 5, 2, 1, 1)
        self.roiPlot = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roiPlot.sizePolicy().hasHeightForWidth())
        self.roiPlot.setSizePolicy(sizePolicy)
        self.roiPlot.setMinimumSize(QtCore.QSize(0, 40))
        self.roiPlot.setObjectName("roiPlot")
        self.MotionCorGroup = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MotionCorGroup.sizePolicy().hasHeightForWidth())
        self.MotionCorGroup.setSizePolicy(sizePolicy)
        self.MotionCorGroup.setMinimumSize(QtCore.QSize(0, 150))
        self.MotionCorGroup.setObjectName("MotionCorGroup")
        self.layoutWidget2 = QtWidgets.QWidget(self.MotionCorGroup)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 1101, 114))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.rigXBox = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigXBox.sizePolicy().hasHeightForWidth())
        self.rigXBox.setSizePolicy(sizePolicy)
        self.rigXBox.setObjectName("rigXBox")
        self.horizontalLayout.addWidget(self.rigXBox)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.rigThreadsBox = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rigThreadsBox.sizePolicy().hasHeightForWidth())
        self.rigThreadsBox.setSizePolicy(sizePolicy)
        self.rigThreadsBox.setObjectName("rigThreadsBox")
        self.horizontalLayout.addWidget(self.rigThreadsBox)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.rigYBox = QtWidgets.QSpinBox(self.layoutWidget2)
        self.rigYBox.setMinimum(1)
        self.rigYBox.setObjectName("rigYBox")
        self.horizontalLayout.addWidget(self.rigYBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_batch_Btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.add_batch_Btn.setObjectName("add_batch_Btn")
        self.horizontalLayout_4.addWidget(self.add_batch_Btn)
        self.motcorr_now_Btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.motcorr_now_Btn.setObjectName("motcorr_now_Btn")
        self.horizontalLayout_4.addWidget(self.motcorr_now_Btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.BatchesLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.BatchesLayout.setContentsMargins(0, 0, 0, 0)
        self.BatchesLayout.setObjectName("BatchesLayout")
        self.batchLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.batchLabel.setObjectName("batchLabel")
        self.BatchesLayout.addWidget(self.batchLabel)
        self.batch_listw = QtWidgets.QListWidget(self.layoutWidget3)
        self.batch_listw.setObjectName("batch_listw")
        self.BatchesLayout.addWidget(self.batch_listw)
        self.motioncorrlistLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.motioncorrlistLabel.setObjectName("motioncorrlistLabel")
        self.BatchesLayout.addWidget(self.motioncorrlistLabel)
        self.motioncorr_listw = QtWidgets.QListWidget(self.layoutWidget3)
        self.motioncorr_listw.setObjectName("motioncorr_listw")
        self.BatchesLayout.addWidget(self.motioncorr_listw)
        self.denoisedlistLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.denoisedlistLabel.setObjectName("denoisedlistLabel")
        self.BatchesLayout.addWidget(self.denoisedlistLabel)
        self.denoised_listw = QtWidgets.QListWidget(self.layoutWidget3)
        self.denoised_listw.setObjectName("denoised_listw")
        self.BatchesLayout.addWidget(self.denoised_listw)
        self.saveselectionBtn = QtWidgets.QPushButton(self.layoutWidget3)
        self.saveselectionBtn.setObjectName("saveselectionBtn")
        self.BatchesLayout.addWidget(self.saveselectionBtn)
        self.gridLayout_2.addWidget(self.splitter_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.checkBox.toggled['bool'].connect(self.checkBox_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.openFileBtn.setText(_translate("Form", "Open file(s)"))
        self.mesfile_label.setText(_translate("Form", "MES file contents"))
        self.imgs_list_label.setText(_translate("Form", "Images/stacks"))
        self.abortBtn.setText(_translate("Form", "Abort"))
        self.exportBtn.setText(_translate("Form", "Export current img"))
        self.motcor_gui_Btn.setText(_translate("Form", "Motion correction"))
        self.add_roi_Btn.setText(_translate("Form", "+ ROI"))
        self.liveupdateBtn.setText(_translate("Form", "Live update plot"))
        self.load_roi_Btn.setText(_translate("Form", "Load ROIs"))
        self.save_roi_Btn.setText(_translate("Form", "Save ROIs"))
        self.resetscaleBtn.setText(_translate("Form", "Reset scale"))
        self.addtoProjBtn.setText(_translate("Form", "Add to Project"))
        self.MotionCorGroup.setTitle(_translate("Form", "Motion correction parameters"))
        self.label.setText(_translate("Form", "decay time: "))
        self.label_2.setText(_translate("Form", " iterations: "))
        self.checkBox.setText(_translate("Form", "Rigid correction"))
        self.label_7.setText(_translate("Form", "max shifts X: "))
        self.label_11.setText(_translate("Form", "max shifts Y: "))
        self.label_12.setText(_translate("Form", "threads: "))
        self.add_batch_Btn.setText(_translate("Form", "Add to batch"))
        self.motcorr_now_Btn.setText(_translate("Form", "Process now"))
        self.checkBox_2.setText(_translate("Form", "Elastic correction"))
        self.label_4.setText(_translate("Form", "strides"))
        self.label_5.setText(_translate("Form", "overlaps"))
        self.label_8.setText(_translate("Form", "upsample:"))
        self.label_3.setText(_translate("Form", "max deviation:"))
        self.batchLabel.setText(_translate("Form", "Batch"))
        self.motioncorrlistLabel.setText(_translate("Form", "Motion Corrected"))
        self.denoisedlistLabel.setText(_translate("Form", "Denoised"))
        self.saveselectionBtn.setText(_translate("Form", "Save selection"))

from ..widgets.GraphicsView import GraphicsView
from ..widgets.HistogramLUTWidget import HistogramLUTWidget
from ..widgets.PlotWidget import PlotWidget
