# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageViewTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1264, 965)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitterBatches = QtWidgets.QSplitter(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterBatches.sizePolicy().hasHeightForWidth())
        self.splitterBatches.setSizePolicy(sizePolicy)
        self.splitterBatches.setOrientation(QtCore.Qt.Horizontal)
        self.splitterBatches.setObjectName("splitterBatches")
        self.splitterLeft = QtWidgets.QSplitter(self.splitterBatches)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterLeft.sizePolicy().hasHeightForWidth())
        self.splitterLeft.setSizePolicy(sizePolicy)
        self.splitterLeft.setOrientation(QtCore.Qt.Vertical)
        self.splitterLeft.setObjectName("splitterLeft")
        self.layoutWidget = QtWidgets.QWidget(self.splitterLeft)
        self.layoutWidget.setObjectName("layoutWidget")
        self.FileMenusLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.FileMenusLayout.setContentsMargins(0, 0, 0, 0)
        self.FileMenusLayout.setObjectName("FileMenusLayout")
        self.btnOpenFiles = QtWidgets.QPushButton(self.layoutWidget)
        self.btnOpenFiles.setObjectName("btnOpenFiles")
        self.FileMenusLayout.addWidget(self.btnOpenFiles, 0, 0, 1, 1)
        self.mesfile_label = QtWidgets.QLabel(self.layoutWidget)
        self.mesfile_label.setObjectName("mesfile_label")
        self.FileMenusLayout.addWidget(self.mesfile_label, 1, 0, 1, 1)
        self.listwTiffs = QtWidgets.QListWidget(self.layoutWidget)
        self.listwTiffs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwTiffs.sizePolicy().hasHeightForWidth())
        self.listwTiffs.setSizePolicy(sizePolicy)
        self.listwTiffs.setObjectName("listwTiffs")
        self.FileMenusLayout.addWidget(self.listwTiffs, 2, 1, 1, 1)
        self.imgs_list_label = QtWidgets.QLabel(self.layoutWidget)
        self.imgs_list_label.setObjectName("imgs_list_label")
        self.FileMenusLayout.addWidget(self.imgs_list_label, 1, 1, 1, 1)
        self.listwMesfile = QtWidgets.QListWidget(self.layoutWidget)
        self.listwMesfile.setEnabled(False)
        self.listwMesfile.setObjectName("listwMesfile")
        self.FileMenusLayout.addWidget(self.listwMesfile, 2, 0, 1, 1)
        self.listwSplits = QtWidgets.QListWidget(self.layoutWidget)
        self.listwSplits.setEnabled(False)
        self.listwSplits.setObjectName("listwSplits")
        self.FileMenusLayout.addWidget(self.listwSplits, 2, 2, 1, 1)
        self.imgs_list_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.imgs_list_label_2.setObjectName("imgs_list_label_2")
        self.FileMenusLayout.addWidget(self.imgs_list_label_2, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitterLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.abortBtn = QtWidgets.QPushButton(self.layoutWidget1)
        self.abortBtn.setEnabled(False)
        self.abortBtn.setObjectName("abortBtn")
        self.gridLayout.addWidget(self.abortBtn, 0, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 2)
        self.btnConcatSeqs = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnConcatSeqs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnConcatSeqs.sizePolicy().hasHeightForWidth())
        self.btnConcatSeqs.setSizePolicy(sizePolicy)
        self.btnConcatSeqs.setMinimumSize(QtCore.QSize(0, 10))
        self.btnConcatSeqs.setMaximumSize(QtCore.QSize(100, 22))
        self.btnConcatSeqs.setObjectName("btnConcatSeqs")
        self.gridLayout.addWidget(self.btnConcatSeqs, 5, 1, 1, 1)
        self.btnSplitSeq = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnSplitSeq.sizePolicy().hasHeightForWidth())
        self.btnSplitSeq.setSizePolicy(sizePolicy)
        self.btnSplitSeq.setMinimumSize(QtCore.QSize(0, 10))
        self.btnSplitSeq.setMaximumSize(QtCore.QSize(100, 22))
        self.btnSplitSeq.setObjectName("btnSplitSeq")
        self.gridLayout.addWidget(self.btnSplitSeq, 4, 1, 1, 1)
        self.btnResetScale = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResetScale.sizePolicy().hasHeightForWidth())
        self.btnResetScale.setSizePolicy(sizePolicy)
        self.btnResetScale.setMinimumSize(QtCore.QSize(0, 10))
        self.btnResetScale.setMaximumSize(QtCore.QSize(100, 22))
        self.btnResetScale.setObjectName("btnResetScale")
        self.gridLayout.addWidget(self.btnResetScale, 6, 1, 1, 1)
        self.btnResetSMap = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnResetSMap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResetSMap.sizePolicy().hasHeightForWidth())
        self.btnResetSMap.setSizePolicy(sizePolicy)
        self.btnResetSMap.setMinimumSize(QtCore.QSize(0, 10))
        self.btnResetSMap.setMaximumSize(QtCore.QSize(100, 22))
        self.btnResetSMap.setObjectName("btnResetSMap")
        self.gridLayout.addWidget(self.btnResetSMap, 5, 2, 1, 1)
        self.btnChangeSMap = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnChangeSMap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnChangeSMap.sizePolicy().hasHeightForWidth())
        self.btnChangeSMap.setSizePolicy(sizePolicy)
        self.btnChangeSMap.setMinimumSize(QtCore.QSize(0, 10))
        self.btnChangeSMap.setMaximumSize(QtCore.QSize(100, 22))
        self.btnChangeSMap.setObjectName("btnChangeSMap")
        self.gridLayout.addWidget(self.btnChangeSMap, 4, 2, 1, 1)
        self.btnSubArray = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnSubArray.sizePolicy().hasHeightForWidth())
        self.btnSubArray.setSizePolicy(sizePolicy)
        self.btnSubArray.setMinimumSize(QtCore.QSize(0, 10))
        self.btnSubArray.setMaximumSize(QtCore.QSize(100, 22))
        self.btnSubArray.setIconSize(QtCore.QSize(16, 16))
        self.btnSubArray.setCheckable(True)
        self.btnSubArray.setObjectName("btnSubArray")
        self.gridLayout.addWidget(self.btnSubArray, 3, 1, 1, 1)
        self.btnAddROI = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnAddROI.sizePolicy().hasHeightForWidth())
        self.btnAddROI.setSizePolicy(sizePolicy)
        self.btnAddROI.setMinimumSize(QtCore.QSize(0, 10))
        self.btnAddROI.setMaximumSize(QtCore.QSize(100, 22))
        self.btnAddROI.setIconSize(QtCore.QSize(16, 16))
        self.btnAddROI.setObjectName("btnAddROI")
        self.gridLayout.addWidget(self.btnAddROI, 3, 2, 1, 1)
        self.comboBoxStimMaps = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBoxStimMaps.setMinimumSize(QtCore.QSize(0, 10))
        self.comboBoxStimMaps.setMaximumSize(QtCore.QSize(16777215, 22))
        self.comboBoxStimMaps.setObjectName("comboBoxStimMaps")
        self.gridLayout.addWidget(self.comboBoxStimMaps, 6, 2, 1, 1)
        self.dockWidget = QtWidgets.QDockWidget(self.layoutWidget1)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphicsView = GraphicsView(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget, 1, 0, 6, 1)
        self.histogram = HistogramLUTWidget(self.layoutWidget1)
        self.histogram.setObjectName("histogram")
        self.gridLayout.addWidget(self.histogram, 1, 1, 2, 2)
        self.roiPlot = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roiPlot.sizePolicy().hasHeightForWidth())
        self.roiPlot.setSizePolicy(sizePolicy)
        self.roiPlot.setMinimumSize(QtCore.QSize(0, 40))
        self.roiPlot.setObjectName("roiPlot")
        self.tabWidget = QtWidgets.QTabWidget(self.splitterLeft)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBatchParams = QtWidgets.QWidget()
        self.tabBatchParams.setEnabled(False)
        self.tabBatchParams.setObjectName("tabBatchParams")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tabBatchParams)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdAnimalID = QtWidgets.QLineEdit(self.tabBatchParams)
        self.lineEdAnimalID.setObjectName("lineEdAnimalID")
        self.horizontalLayout_2.addWidget(self.lineEdAnimalID)
        self.lineEdTrialID = QtWidgets.QLineEdit(self.tabBatchParams)
        self.lineEdTrialID.setObjectName("lineEdTrialID")
        self.horizontalLayout_2.addWidget(self.lineEdTrialID)
        self.lineEdGenotype = QtWidgets.QLineEdit(self.tabBatchParams)
        self.lineEdGenotype.setObjectName("lineEdGenotype")
        self.horizontalLayout_2.addWidget(self.lineEdGenotype)
        self.btnSetID = QtWidgets.QPushButton(self.tabBatchParams)
        self.btnSetID.setObjectName("btnSetID")
        self.horizontalLayout_2.addWidget(self.btnSetID)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.rigMotCheckBox = QtWidgets.QCheckBox(self.tabBatchParams)
        self.rigMotCheckBox.setObjectName("rigMotCheckBox")
        self.verticalLayout_2.addWidget(self.rigMotCheckBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_7 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spinboxX = QtWidgets.QSpinBox(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinboxX.sizePolicy().hasHeightForWidth())
        self.spinboxX.setSizePolicy(sizePolicy)
        self.spinboxX.setObjectName("spinboxX")
        self.horizontalLayout.addWidget(self.spinboxX)
        self.label_11 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.spinboxY = QtWidgets.QSpinBox(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinboxY.sizePolicy().hasHeightForWidth())
        self.spinboxY.setSizePolicy(sizePolicy)
        self.spinboxY.setObjectName("spinboxY")
        self.horizontalLayout.addWidget(self.spinboxY)
        self.label_12 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.spinboxThreads = QtWidgets.QSpinBox(self.tabBatchParams)
        self.spinboxThreads.setMinimum(1)
        self.spinboxThreads.setObjectName("spinboxThreads")
        self.horizontalLayout.addWidget(self.spinboxThreads)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinboxIter = QtWidgets.QSpinBox(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinboxIter.sizePolicy().hasHeightForWidth())
        self.spinboxIter.setSizePolicy(sizePolicy)
        self.spinboxIter.setObjectName("spinboxIter")
        self.horizontalLayout_4.addWidget(self.spinboxIter)
        self.label_8 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinboxUpsample = QtWidgets.QSpinBox(self.tabBatchParams)
        self.spinboxUpsample.setMinimum(1)
        self.spinboxUpsample.setObjectName("spinboxUpsample")
        self.horizontalLayout_4.addWidget(self.spinboxUpsample)
        self.label_3 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinboxMaxDev = QtWidgets.QSpinBox(self.tabBatchParams)
        self.spinboxMaxDev.setObjectName("spinboxMaxDev")
        self.horizontalLayout_4.addWidget(self.spinboxMaxDev)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.labelStridesValue = QtWidgets.QLabel(self.tabBatchParams)
        self.labelStridesValue.setObjectName("labelStridesValue")
        self.horizontalLayout_6.addWidget(self.labelStridesValue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.sliderStrides = QtWidgets.QSlider(self.tabBatchParams)
        self.sliderStrides.setOrientation(QtCore.Qt.Horizontal)
        self.sliderStrides.setObjectName("sliderStrides")
        self.verticalLayout.addWidget(self.sliderStrides)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.labelOverlapsValue = QtWidgets.QLabel(self.tabBatchParams)
        self.labelOverlapsValue.setObjectName("labelOverlapsValue")
        self.horizontalLayout_5.addWidget(self.labelOverlapsValue)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sliderOverlaps = QtWidgets.QSlider(self.tabBatchParams)
        self.sliderOverlaps.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOverlaps.setObjectName("sliderOverlaps")
        self.horizontalLayout_3.addWidget(self.sliderOverlaps)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.btnAddToBatch = QtWidgets.QPushButton(self.tabBatchParams)
        self.btnAddToBatch.setObjectName("btnAddToBatch")
        self.horizontalLayout_9.addWidget(self.btnAddToBatch)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tabBatchParams, "")
        self.tabROIs = QtWidgets.QWidget()
        self.tabROIs.setEnabled(False)
        self.tabROIs.setMinimumSize(QtCore.QSize(0, 0))
        self.tabROIs.setObjectName("tabROIs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabROIs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdROIDef1 = QtWidgets.QLineEdit(self.tabROIs)
        self.lineEdROIDef1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdROIDef1.sizePolicy().hasHeightForWidth())
        self.lineEdROIDef1.setSizePolicy(sizePolicy)
        self.lineEdROIDef1.setObjectName("lineEdROIDef1")
        self.gridLayout_2.addWidget(self.lineEdROIDef1, 1, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnAddCurrEnvToProj = QtWidgets.QPushButton(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnAddCurrEnvToProj.sizePolicy().hasHeightForWidth())
        self.btnAddCurrEnvToProj.setSizePolicy(sizePolicy)
        self.btnAddCurrEnvToProj.setMinimumSize(QtCore.QSize(0, 10))
        self.btnAddCurrEnvToProj.setMaximumSize(QtCore.QSize(100, 30))
        self.btnAddCurrEnvToProj.setObjectName("btnAddCurrEnvToProj")
        self.verticalLayout_4.addWidget(self.btnAddCurrEnvToProj)
        self.btnSaveChangesToProj = QtWidgets.QPushButton(self.tabROIs)
        self.btnSaveChangesToProj.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnSaveChangesToProj.sizePolicy().hasHeightForWidth())
        self.btnSaveChangesToProj.setSizePolicy(sizePolicy)
        self.btnSaveChangesToProj.setMinimumSize(QtCore.QSize(0, 10))
        self.btnSaveChangesToProj.setMaximumSize(QtCore.QSize(100, 30))
        self.btnSaveChangesToProj.setObjectName("btnSaveChangesToProj")
        self.verticalLayout_4.addWidget(self.btnSaveChangesToProj)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 3, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.checkBoxShowAllROIs = QtWidgets.QCheckBox(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowAllROIs.sizePolicy().hasHeightForWidth())
        self.checkBoxShowAllROIs.setSizePolicy(sizePolicy)
        self.checkBoxShowAllROIs.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBoxShowAllROIs.setChecked(True)
        self.checkBoxShowAllROIs.setObjectName("checkBoxShowAllROIs")
        self.horizontalLayout_7.addWidget(self.checkBoxShowAllROIs)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listwROIs = QtWidgets.QListWidget(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwROIs.sizePolicy().hasHeightForWidth())
        self.listwROIs.setSizePolicy(sizePolicy)
        self.listwROIs.setMinimumSize(QtCore.QSize(0, 0))
        self.listwROIs.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listwROIs.setObjectName("listwROIs")
        self.horizontalLayout_8.addWidget(self.listwROIs)
        self.listwROIDefs = QtWidgets.QListWidget(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwROIDefs.sizePolicy().hasHeightForWidth())
        self.listwROIDefs.setSizePolicy(sizePolicy)
        self.listwROIDefs.setMinimumSize(QtCore.QSize(0, 0))
        self.listwROIDefs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listwROIDefs.setObjectName("listwROIDefs")
        self.horizontalLayout_8.addWidget(self.listwROIDefs)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 5, 1)
        self.textBoxComments = QtWidgets.QPlainTextEdit(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBoxComments.sizePolicy().hasHeightForWidth())
        self.textBoxComments.setSizePolicy(sizePolicy)
        self.textBoxComments.setObjectName("textBoxComments")
        self.gridLayout_2.addWidget(self.textBoxComments, 0, 2, 5, 1)
        self.BtnSetROIDefs = QtWidgets.QPushButton(self.tabROIs)
        self.BtnSetROIDefs.setObjectName("BtnSetROIDefs")
        self.gridLayout_2.addWidget(self.BtnSetROIDefs, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(202, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(92, 72, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 3, 2, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabROIs, "")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitterBatches)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.BatchesLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.BatchesLayout.setContentsMargins(0, 0, 0, 0)
        self.BatchesLayout.setObjectName("BatchesLayout")
        self.batchLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.batchLabel.setObjectName("batchLabel")
        self.BatchesLayout.addWidget(self.batchLabel)
        self.listwBatch = QtWidgets.QListWidget(self.layoutWidget2)
        self.listwBatch.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listwBatch.setObjectName("listwBatch")
        self.BatchesLayout.addWidget(self.listwBatch)
        self.motioncorrlistLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.motioncorrlistLabel.setObjectName("motioncorrlistLabel")
        self.BatchesLayout.addWidget(self.motioncorrlistLabel)
        self.listwMotCor = QtWidgets.QListWidget(self.layoutWidget2)
        self.listwMotCor.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listwMotCor.setObjectName("listwMotCor")
        self.BatchesLayout.addWidget(self.listwMotCor)
        self.denoisedlistLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.denoisedlistLabel.setObjectName("denoisedlistLabel")
        self.BatchesLayout.addWidget(self.denoisedlistLabel)
        self.listwDenoised = QtWidgets.QListWidget(self.layoutWidget2)
        self.listwDenoised.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listwDenoised.setObjectName("listwDenoised")
        self.BatchesLayout.addWidget(self.listwDenoised)
        self.btnStartBatch = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnStartBatch.setEnabled(False)
        self.btnStartBatch.setObjectName("btnStartBatch")
        self.BatchesLayout.addWidget(self.btnStartBatch)
        self.btnOpenBatch = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnOpenBatch.setObjectName("btnOpenBatch")
        self.BatchesLayout.addWidget(self.btnOpenBatch)
        self.BtnAddSelProj = QtWidgets.QPushButton(self.layoutWidget2)
        self.BtnAddSelProj.setEnabled(False)
        self.BtnAddSelProj.setObjectName("BtnAddSelProj")
        self.BatchesLayout.addWidget(self.BtnAddSelProj)
        self.gridLayout_3.addWidget(self.splitterBatches, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.sliderStrides.valueChanged['int'].connect(self.labelStridesValue.setNum)
        self.sliderOverlaps.valueChanged['int'].connect(self.labelOverlapsValue.setNum)
        self.rigMotCheckBox.toggled['bool'].connect(self.btnAddToBatch.setEnabled)
        self.lineEdROIDef1.returnPressed.connect(self.BtnSetROIDefs.click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnOpenFiles.setText(_translate("Form", "Open file(s)"))
        self.mesfile_label.setText(_translate("Form", "MES file contents:"))
        self.imgs_list_label.setText(_translate("Form", "Images/stacks:"))
        self.imgs_list_label_2.setText(_translate("Form", "Splits of seq:"))
        self.abortBtn.setText(_translate("Form", "Abort"))
        self.btnConcatSeqs.setText(_translate("Form", "Concat seqs"))
        self.btnSplitSeq.setText(_translate("Form", "Split seq"))
        self.btnResetScale.setText(_translate("Form", "Reset scale"))
        self.btnResetSMap.setToolTip(_translate("Form", "Reset the Stimulus Map to the one set for this mes file"))
        self.btnResetSMap.setText(_translate("Form", "Reset sMap"))
        self.btnChangeSMap.setToolTip(_translate("Form", "Set a Stimulus Map for only the image currently open"))
        self.btnChangeSMap.setText(_translate("Form", "Change sMap"))
        self.btnSubArray.setText(_translate("Form", "Subarray"))
        self.btnAddROI.setText(_translate("Form", "+ ROI"))
        self.lineEdAnimalID.setPlaceholderText(_translate("Form", "Animal ID"))
        self.lineEdTrialID.setPlaceholderText(_translate("Form", "Trial ID"))
        self.lineEdGenotype.setPlaceholderText(_translate("Form", "Genotype"))
        self.btnSetID.setText(_translate("Form", "Set"))
        self.rigMotCheckBox.setText(_translate("Form", "Motion Correction"))
        self.pushButton.setText(_translate("Form", "Measure"))
        self.label_7.setText(_translate("Form", " max shifts X (pixels): "))
        self.label_11.setText(_translate("Form", " max shifts Y (pixels): "))
        self.label_12.setText(_translate("Form", " threads: "))
        self.label_2.setText(_translate("Form", " iterations for rigid: "))
        self.label_8.setText(_translate("Form", " upsample grid:"))
        self.label_3.setText(_translate("Form", " max deviation from rigid:"))
        self.label_4.setText(_translate("Form", "strides (pixels): "))
        self.labelStridesValue.setText(_translate("Form", "labelStridesValue"))
        self.label_5.setText(_translate("Form", "overlaps (pixels): "))
        self.labelOverlapsValue.setText(_translate("Form", "labelOverlapsValue"))
        self.btnAddToBatch.setText(_translate("Form", "Add to batch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatchParams), _translate("Form", "Batch Params"))
        self.btnAddCurrEnvToProj.setText(_translate("Form", "Add to Project"))
        self.btnSaveChangesToProj.setText(_translate("Form", "Save changes"))
        self.label.setText(_translate("Form", "ROIs:   "))
        self.checkBoxShowAllROIs.setText(_translate("Form", "Show all on image"))
        self.textBoxComments.setPlaceholderText(_translate("Form", "Comments"))
        self.BtnSetROIDefs.setText(_translate("Form", "Set ROI tag"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabROIs), _translate("Form", "ROIs"))
        self.batchLabel.setText(_translate("Form", "Batch"))
        self.motioncorrlistLabel.setText(_translate("Form", "Motion Corrected"))
        self.denoisedlistLabel.setText(_translate("Form", "Denoised"))
        self.btnStartBatch.setText(_translate("Form", "Start Batch"))
        self.btnOpenBatch.setText(_translate("Form", "Open Batch"))
        self.BtnAddSelProj.setText(_translate("Form", "Add selection to project"))

from ..widgets.GraphicsView import GraphicsView
from ..widgets.HistogramLUTWidget import HistogramLUTWidget
from pyqtgraphCore import PlotWidget
