# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageViewTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1092, 651)
        self.gridLayout_10 = QtWidgets.QGridLayout(Form)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.splitterHighest = QtWidgets.QSplitter(Form)
        self.splitterHighest.setOrientation(QtCore.Qt.Vertical)
        self.splitterHighest.setObjectName("splitterHighest")
        self.splitterFilesImage = QtWidgets.QSplitter(self.splitterHighest)
        self.splitterFilesImage.setOrientation(QtCore.Qt.Vertical)
        self.splitterFilesImage.setObjectName("splitterFilesImage")
        self.layoutWidget = QtWidgets.QWidget(self.splitterFilesImage)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
        self.mesfile_label = QtWidgets.QLabel(self.page_3)
        self.mesfile_label.setObjectName("mesfile_label")
        self.gridLayout_7.addWidget(self.mesfile_label, 0, 2, 1, 1)
        self.btnOpenMesFiles = QtWidgets.QPushButton(self.page_3)
        self.btnOpenMesFiles.setObjectName("btnOpenMesFiles")
        self.gridLayout_7.addWidget(self.btnOpenMesFiles, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 3, 1, 1)
        self.btnTiffPage = QtWidgets.QPushButton(self.page_3)
        self.btnTiffPage.setMinimumSize(QtCore.QSize(0, 20))
        self.btnTiffPage.setMaximumSize(QtCore.QSize(80, 20))
        self.btnTiffPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnTiffPage.setBaseSize(QtCore.QSize(0, 0))
        self.btnTiffPage.setDefault(False)
        self.btnTiffPage.setFlat(False)
        self.btnTiffPage.setObjectName("btnTiffPage")
        self.gridLayout_7.addWidget(self.btnTiffPage, 0, 4, 1, 1)
        self.listwMesfile = QtWidgets.QListWidget(self.page_3)
        self.listwMesfile.setEnabled(False)
        self.listwMesfile.setObjectName("listwMesfile")
        self.gridLayout_7.addWidget(self.listwMesfile, 2, 0, 1, 5)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnOpenTiff = QtWidgets.QPushButton(self.page_4)
        self.btnOpenTiff.setObjectName("btnOpenTiff")
        self.gridLayout_5.addWidget(self.btnOpenTiff, 1, 0, 1, 1)
        self.listwTiffs = QtWidgets.QListWidget(self.page_4)
        self.listwTiffs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwTiffs.sizePolicy().hasHeightForWidth())
        self.listwTiffs.setSizePolicy(sizePolicy)
        self.listwTiffs.setObjectName("listwTiffs")
        self.gridLayout_5.addWidget(self.listwTiffs, 2, 0, 1, 5)
        self.btnSplitsPage = QtWidgets.QPushButton(self.page_4)
        self.btnSplitsPage.setMinimumSize(QtCore.QSize(0, 20))
        self.btnSplitsPage.setMaximumSize(QtCore.QSize(80, 20))
        self.btnSplitsPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnSplitsPage.setBaseSize(QtCore.QSize(0, 0))
        self.btnSplitsPage.setDefault(False)
        self.btnSplitsPage.setFlat(False)
        self.btnSplitsPage.setObjectName("btnSplitsPage")
        self.gridLayout_5.addWidget(self.btnSplitsPage, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(80, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 1, 1, 1)
        self.imgs_list_label = QtWidgets.QLabel(self.page_4)
        self.imgs_list_label.setObjectName("imgs_list_label")
        self.gridLayout_5.addWidget(self.imgs_list_label, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(109, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 0, 1, 1)
        self.imgs_list_label_2 = QtWidgets.QLabel(self.page_5)
        self.imgs_list_label_2.setObjectName("imgs_list_label_2")
        self.gridLayout_6.addWidget(self.imgs_list_label_2, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(109, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 2, 1, 1)
        self.btnMesPage = QtWidgets.QPushButton(self.page_5)
        self.btnMesPage.setMinimumSize(QtCore.QSize(0, 20))
        self.btnMesPage.setMaximumSize(QtCore.QSize(80, 20))
        self.btnMesPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnMesPage.setBaseSize(QtCore.QSize(0, 0))
        self.btnMesPage.setDefault(False)
        self.btnMesPage.setFlat(False)
        self.btnMesPage.setObjectName("btnMesPage")
        self.gridLayout_6.addWidget(self.btnMesPage, 0, 3, 1, 1)
        self.listwSplits = QtWidgets.QListWidget(self.page_5)
        self.listwSplits.setEnabled(False)
        self.listwSplits.setObjectName("listwSplits")
        self.gridLayout_6.addWidget(self.listwSplits, 1, 0, 1, 4)
        self.stackedWidget.addWidget(self.page_5)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout.setObjectName("gridLayout")
        self.listwBatch = QtWidgets.QListWidget(self.page_6)
        self.listwBatch.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listwBatch.setObjectName("listwBatch")
        self.gridLayout.addWidget(self.listwBatch, 2, 0, 1, 5)
        self.btnOpenBatch = QtWidgets.QPushButton(self.page_6)
        self.btnOpenBatch.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnOpenBatch.setObjectName("btnOpenBatch")
        self.gridLayout.addWidget(self.btnOpenBatch, 3, 0, 1, 1)
        self.btnMCPage = QtWidgets.QPushButton(self.page_6)
        self.btnMCPage.setMinimumSize(QtCore.QSize(0, 20))
        self.btnMCPage.setMaximumSize(QtCore.QSize(125, 20))
        self.btnMCPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnMCPage.setBaseSize(QtCore.QSize(0, 0))
        self.btnMCPage.setDefault(False)
        self.btnMCPage.setFlat(False)
        self.btnMCPage.setObjectName("btnMCPage")
        self.gridLayout.addWidget(self.btnMCPage, 0, 4, 1, 1)
        self.batchLabel = QtWidgets.QLabel(self.page_6)
        self.batchLabel.setObjectName("batchLabel")
        self.gridLayout.addWidget(self.batchLabel, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 3, 1, 1)
        self.btnStartBatch = QtWidgets.QPushButton(self.page_6)
        self.btnStartBatch.setEnabled(False)
        self.btnStartBatch.setMaximumSize(QtCore.QSize(87, 16777215))
        self.btnStartBatch.setObjectName("btnStartBatch")
        self.gridLayout.addWidget(self.btnStartBatch, 3, 2, 1, 1)
        self.btnRemoveFromBatch = QtWidgets.QPushButton(self.page_6)
        self.btnRemoveFromBatch.setEnabled(False)
        self.btnRemoveFromBatch.setObjectName("btnRemoveFromBatch")
        self.gridLayout.addWidget(self.btnRemoveFromBatch, 3, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.motioncorrlistLabel = QtWidgets.QLabel(self.page_7)
        self.motioncorrlistLabel.setObjectName("motioncorrlistLabel")
        self.gridLayout_3.addWidget(self.motioncorrlistLabel, 0, 1, 1, 1)
        self.btnDenPage = QtWidgets.QPushButton(self.page_7)
        self.btnDenPage.setMinimumSize(QtCore.QSize(0, 20))
        self.btnDenPage.setMaximumSize(QtCore.QSize(125, 20))
        self.btnDenPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnDenPage.setBaseSize(QtCore.QSize(0, 0))
        self.btnDenPage.setDefault(False)
        self.btnDenPage.setFlat(False)
        self.btnDenPage.setObjectName("btnDenPage")
        self.gridLayout_3.addWidget(self.btnDenPage, 0, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(80, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 2, 1, 1)
        self.btnMotCorSearchDir = QtWidgets.QPushButton(self.page_7)
        self.btnMotCorSearchDir.setObjectName("btnMotCorSearchDir")
        self.gridLayout_3.addWidget(self.btnMotCorSearchDir, 2, 0, 1, 1)
        self.listwMotCor = QtWidgets.QListWidget(self.page_7)
        self.listwMotCor.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listwMotCor.setObjectName("listwMotCor")
        self.gridLayout_3.addWidget(self.listwMotCor, 1, 0, 1, 4)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnBatchPage = QtWidgets.QPushButton(self.page_8)
        self.btnBatchPage.setMinimumSize(QtCore.QSize(0, 20))
        self.btnBatchPage.setMaximumSize(QtCore.QSize(125, 20))
        self.btnBatchPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.btnBatchPage.setBaseSize(QtCore.QSize(0, 0))
        self.btnBatchPage.setDefault(False)
        self.btnBatchPage.setFlat(False)
        self.btnBatchPage.setObjectName("btnBatchPage")
        self.gridLayout_4.addWidget(self.btnBatchPage, 2, 3, 1, 1)
        self.denoisedlistLabel = QtWidgets.QLabel(self.page_8)
        self.denoisedlistLabel.setObjectName("denoisedlistLabel")
        self.gridLayout_4.addWidget(self.denoisedlistLabel, 2, 1, 1, 1)
        self.listwDenoised = QtWidgets.QListWidget(self.page_8)
        self.listwDenoised.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listwDenoised.setObjectName("listwDenoised")
        self.gridLayout_4.addWidget(self.listwDenoised, 5, 0, 1, 4)
        spacerItem10 = QtWidgets.QSpacerItem(105, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 2, 2, 1, 1)
        self.stackedWidget_2.addWidget(self.page_8)
        self.horizontalLayout_11.addWidget(self.stackedWidget_2)
        self.toolBox = QtWidgets.QToolBox(self.layoutWidget)
        self.toolBox.setEnabled(True)
        self.toolBox.setMinimumSize(QtCore.QSize(331, 161))
        self.toolBox.setMaximumSize(QtCore.QSize(331, 16777215))
        self.toolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setMidLineWidth(1)
        self.toolBox.setObjectName("toolBox")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 329, 95))
        self.page_9.setObjectName("page_9")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_9)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 0, 311, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnChangeSMap = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnChangeSMap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnChangeSMap.sizePolicy().hasHeightForWidth())
        self.btnChangeSMap.setSizePolicy(sizePolicy)
        self.btnChangeSMap.setMinimumSize(QtCore.QSize(0, 10))
        self.btnChangeSMap.setMaximumSize(QtCore.QSize(100, 25))
        self.btnChangeSMap.setObjectName("btnChangeSMap")
        self.gridLayout_9.addWidget(self.btnChangeSMap, 1, 2, 1, 1)
        self.btnImportSMap = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnImportSMap.sizePolicy().hasHeightForWidth())
        self.btnImportSMap.setSizePolicy(sizePolicy)
        self.btnImportSMap.setMinimumSize(QtCore.QSize(0, 10))
        self.btnImportSMap.setMaximumSize(QtCore.QSize(100, 25))
        self.btnImportSMap.setIconSize(QtCore.QSize(16, 16))
        self.btnImportSMap.setCheckable(True)
        self.btnImportSMap.setObjectName("btnImportSMap")
        self.gridLayout_9.addWidget(self.btnImportSMap, 0, 2, 1, 1)
        self.btnResetSMap = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnResetSMap.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResetSMap.sizePolicy().hasHeightForWidth())
        self.btnResetSMap.setSizePolicy(sizePolicy)
        self.btnResetSMap.setMinimumSize(QtCore.QSize(0, 10))
        self.btnResetSMap.setMaximumSize(QtCore.QSize(100, 25))
        self.btnResetSMap.setObjectName("btnResetSMap")
        self.gridLayout_9.addWidget(self.btnResetSMap, 2, 2, 1, 1)
        self.btnResetScale = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnResetScale.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnResetScale.sizePolicy().hasHeightForWidth())
        self.btnResetScale.setSizePolicy(sizePolicy)
        self.btnResetScale.setMinimumSize(QtCore.QSize(0, 10))
        self.btnResetScale.setMaximumSize(QtCore.QSize(100, 25))
        self.btnResetScale.setObjectName("btnResetScale")
        self.gridLayout_9.addWidget(self.btnResetScale, 1, 0, 1, 1)
        self.btnCrop = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnCrop.sizePolicy().hasHeightForWidth())
        self.btnCrop.setSizePolicy(sizePolicy)
        self.btnCrop.setMinimumSize(QtCore.QSize(0, 10))
        self.btnCrop.setMaximumSize(QtCore.QSize(100, 25))
        self.btnCrop.setIconSize(QtCore.QSize(16, 16))
        self.btnCrop.setCheckable(True)
        self.btnCrop.setObjectName("btnCrop")
        self.gridLayout_9.addWidget(self.btnCrop, 0, 0, 1, 1)
        self.btnAddROI = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnAddROI.sizePolicy().hasHeightForWidth())
        self.btnAddROI.setSizePolicy(sizePolicy)
        self.btnAddROI.setMinimumSize(QtCore.QSize(0, 10))
        self.btnAddROI.setMaximumSize(QtCore.QSize(100, 25))
        self.btnAddROI.setIconSize(QtCore.QSize(16, 16))
        self.btnAddROI.setObjectName("btnAddROI")
        self.gridLayout_9.addWidget(self.btnAddROI, 0, 1, 1, 1)
        self.btnPlot = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnPlot.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnPlot.sizePolicy().hasHeightForWidth())
        self.btnPlot.setSizePolicy(sizePolicy)
        self.btnPlot.setMinimumSize(QtCore.QSize(0, 10))
        self.btnPlot.setMaximumSize(QtCore.QSize(100, 25))
        self.btnPlot.setIconSize(QtCore.QSize(16, 16))
        self.btnPlot.setCheckable(True)
        self.btnPlot.setChecked(True)
        self.btnPlot.setObjectName("btnPlot")
        self.gridLayout_9.addWidget(self.btnPlot, 2, 0, 1, 1)
        self.btnEditMetaData = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnEditMetaData.sizePolicy().hasHeightForWidth())
        self.btnEditMetaData.setSizePolicy(sizePolicy)
        self.btnEditMetaData.setMinimumSize(QtCore.QSize(0, 10))
        self.btnEditMetaData.setMaximumSize(QtCore.QSize(100, 25))
        self.btnEditMetaData.setIconSize(QtCore.QSize(16, 16))
        self.btnEditMetaData.setObjectName("btnEditMetaData")
        self.gridLayout_9.addWidget(self.btnEditMetaData, 1, 1, 1, 1)
        self.toolBox.addItem(self.page_9, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 329, 95))
        self.page_10.setObjectName("page_10")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_10)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 206, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btnSplitSeq = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnSplitSeq.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnSplitSeq.sizePolicy().hasHeightForWidth())
        self.btnSplitSeq.setSizePolicy(sizePolicy)
        self.btnSplitSeq.setMinimumSize(QtCore.QSize(0, 10))
        self.btnSplitSeq.setMaximumSize(QtCore.QSize(100, 25))
        self.btnSplitSeq.setObjectName("btnSplitSeq")
        self.gridLayout_11.addWidget(self.btnSplitSeq, 0, 0, 1, 1)
        self.btnDoneSplitSeqs = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnDoneSplitSeqs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnDoneSplitSeqs.sizePolicy().hasHeightForWidth())
        self.btnDoneSplitSeqs.setSizePolicy(sizePolicy)
        self.btnDoneSplitSeqs.setMinimumSize(QtCore.QSize(100, 10))
        self.btnDoneSplitSeqs.setMaximumSize(QtCore.QSize(100, 25))
        self.btnDoneSplitSeqs.setObjectName("btnDoneSplitSeqs")
        self.gridLayout_11.addWidget(self.btnDoneSplitSeqs, 0, 1, 1, 1)
        self.btnPlotSplits = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnPlotSplits.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnPlotSplits.sizePolicy().hasHeightForWidth())
        self.btnPlotSplits.setSizePolicy(sizePolicy)
        self.btnPlotSplits.setMinimumSize(QtCore.QSize(0, 10))
        self.btnPlotSplits.setMaximumSize(QtCore.QSize(100, 25))
        self.btnPlotSplits.setObjectName("btnPlotSplits")
        self.gridLayout_11.addWidget(self.btnPlotSplits, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_10, "")
        self.horizontalLayout_11.addWidget(self.toolBox)
        self.splitter = QtWidgets.QSplitter(self.splitterFilesImage)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_8.addWidget(self.progressBar, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 18))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 3, 2, 1, 1)
        self.comboBoxStimMaps = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBoxStimMaps.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBoxStimMaps.setMaximumSize(QtCore.QSize(16777215, 22))
        self.comboBoxStimMaps.setObjectName("comboBoxStimMaps")
        self.gridLayout_8.addWidget(self.comboBoxStimMaps, 4, 2, 1, 1)
        self.btnExportWorkEnv = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnExportWorkEnv.setObjectName("btnExportWorkEnv")
        self.gridLayout_8.addWidget(self.btnExportWorkEnv, 0, 2, 1, 1)
        self.btnAbort = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnAbort.setEnabled(False)
        self.btnAbort.setObjectName("btnAbort")
        self.gridLayout_8.addWidget(self.btnAbort, 0, 1, 1, 1)
        self.graphicsView = GraphicsView(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_8.addWidget(self.graphicsView, 1, 0, 5, 2)
        self.histogram = HistogramLUTWidget(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        self.histogram.setMinimumSize(QtCore.QSize(150, 0))
        self.histogram.setMaximumSize(QtCore.QSize(150, 16777215))
        self.histogram.setObjectName("histogram")
        self.gridLayout_8.addWidget(self.histogram, 1, 2, 2, 1)
        self.roiPlot = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roiPlot.sizePolicy().hasHeightForWidth())
        self.roiPlot.setSizePolicy(sizePolicy)
        self.roiPlot.setMinimumSize(QtCore.QSize(0, 40))
        self.roiPlot.setObjectName("roiPlot")
        self.tabWidget = QtWidgets.QTabWidget(self.splitterHighest)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBatchParams = QtWidgets.QWidget()
        self.tabBatchParams.setEnabled(False)
        self.tabBatchParams.setObjectName("tabBatchParams")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tabBatchParams)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdAnimalID = QtWidgets.QLineEdit(self.tabBatchParams)
        self.lineEdAnimalID.setObjectName("lineEdAnimalID")
        self.horizontalLayout_2.addWidget(self.lineEdAnimalID)
        self.lineEdTrialID = QtWidgets.QLineEdit(self.tabBatchParams)
        self.lineEdTrialID.setObjectName("lineEdTrialID")
        self.horizontalLayout_2.addWidget(self.lineEdTrialID)
        self.lineEdGenotype = QtWidgets.QLineEdit(self.tabBatchParams)
        self.lineEdGenotype.setObjectName("lineEdGenotype")
        self.horizontalLayout_2.addWidget(self.lineEdGenotype)
        self.btnSetID = QtWidgets.QPushButton(self.tabBatchParams)
        self.btnSetID.setObjectName("btnSetID")
        self.horizontalLayout_2.addWidget(self.btnSetID)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.rigMotCheckBox = QtWidgets.QCheckBox(self.tabBatchParams)
        self.rigMotCheckBox.setObjectName("rigMotCheckBox")
        self.verticalLayout_2.addWidget(self.rigMotCheckBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnMeasureDistance = QtWidgets.QPushButton(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasureDistance.sizePolicy().hasHeightForWidth())
        self.btnMeasureDistance.setSizePolicy(sizePolicy)
        self.btnMeasureDistance.setMinimumSize(QtCore.QSize(0, 0))
        self.btnMeasureDistance.setMaximumSize(QtCore.QSize(65, 16777215))
        self.btnMeasureDistance.setCheckable(True)
        self.btnMeasureDistance.setObjectName("btnMeasureDistance")
        self.horizontalLayout.addWidget(self.btnMeasureDistance)
        self.label_7 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spinboxX = QtWidgets.QSpinBox(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinboxX.sizePolicy().hasHeightForWidth())
        self.spinboxX.setSizePolicy(sizePolicy)
        self.spinboxX.setObjectName("spinboxX")
        self.horizontalLayout.addWidget(self.spinboxX)
        self.label_11 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.spinboxY = QtWidgets.QSpinBox(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinboxY.sizePolicy().hasHeightForWidth())
        self.spinboxY.setSizePolicy(sizePolicy)
        self.spinboxY.setObjectName("spinboxY")
        self.horizontalLayout.addWidget(self.spinboxY)
        self.label_12 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.spinboxThreads = QtWidgets.QSpinBox(self.tabBatchParams)
        self.spinboxThreads.setMinimum(1)
        self.spinboxThreads.setObjectName("spinboxThreads")
        self.horizontalLayout.addWidget(self.spinboxThreads)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinboxIter = QtWidgets.QSpinBox(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinboxIter.sizePolicy().hasHeightForWidth())
        self.spinboxIter.setSizePolicy(sizePolicy)
        self.spinboxIter.setMinimum(1)
        self.spinboxIter.setObjectName("spinboxIter")
        self.horizontalLayout_4.addWidget(self.spinboxIter)
        self.label_8 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinboxUpsample = QtWidgets.QSpinBox(self.tabBatchParams)
        self.spinboxUpsample.setMinimum(1)
        self.spinboxUpsample.setProperty("value", 4)
        self.spinboxUpsample.setObjectName("spinboxUpsample")
        self.horizontalLayout_4.addWidget(self.spinboxUpsample)
        self.label_3 = QtWidgets.QLabel(self.tabBatchParams)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinboxMaxDev = QtWidgets.QSpinBox(self.tabBatchParams)
        self.spinboxMaxDev.setProperty("value", 3)
        self.spinboxMaxDev.setObjectName("spinboxMaxDev")
        self.horizontalLayout_4.addWidget(self.spinboxMaxDev)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.labelStridesValue = QtWidgets.QLabel(self.tabBatchParams)
        self.labelStridesValue.setText("")
        self.labelStridesValue.setObjectName("labelStridesValue")
        self.horizontalLayout_6.addWidget(self.labelStridesValue)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.sliderStrides = QtWidgets.QSlider(self.tabBatchParams)
        self.sliderStrides.setMinimum(1)
        self.sliderStrides.setOrientation(QtCore.Qt.Horizontal)
        self.sliderStrides.setObjectName("sliderStrides")
        self.verticalLayout.addWidget(self.sliderStrides)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tabBatchParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.labelOverlapsValue = QtWidgets.QLabel(self.tabBatchParams)
        self.labelOverlapsValue.setText("")
        self.labelOverlapsValue.setObjectName("labelOverlapsValue")
        self.horizontalLayout_5.addWidget(self.labelOverlapsValue)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.btnShowQuilt = QtWidgets.QPushButton(self.tabBatchParams)
        self.btnShowQuilt.setCheckable(True)
        self.btnShowQuilt.setObjectName("btnShowQuilt")
        self.horizontalLayout_5.addWidget(self.btnShowQuilt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sliderOverlaps = QtWidgets.QSlider(self.tabBatchParams)
        self.sliderOverlaps.setMinimum(1)
        self.sliderOverlaps.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOverlaps.setObjectName("sliderOverlaps")
        self.horizontalLayout_3.addWidget(self.sliderOverlaps)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_3)
        self.btnAddToBatch = QtWidgets.QPushButton(self.tabBatchParams)
        self.btnAddToBatch.setObjectName("btnAddToBatch")
        self.horizontalLayout_9.addWidget(self.btnAddToBatch)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tabBatchParams, "")
        self.tabROIs = QtWidgets.QWidget()
        self.tabROIs.setEnabled(False)
        self.tabROIs.setMinimumSize(QtCore.QSize(0, 0))
        self.tabROIs.setObjectName("tabROIs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabROIs)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(203, 114, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 3, 1, 2, 1)
        self.BtnSetROIDefs = QtWidgets.QPushButton(self.tabROIs)
        self.BtnSetROIDefs.setObjectName("BtnSetROIDefs")
        self.gridLayout_2.addWidget(self.BtnSetROIDefs, 2, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(92, 146, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 2, 3, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnAddCurrEnvToProj = QtWidgets.QPushButton(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnAddCurrEnvToProj.sizePolicy().hasHeightForWidth())
        self.btnAddCurrEnvToProj.setSizePolicy(sizePolicy)
        self.btnAddCurrEnvToProj.setMinimumSize(QtCore.QSize(0, 26))
        self.btnAddCurrEnvToProj.setMaximumSize(QtCore.QSize(100, 30))
        self.btnAddCurrEnvToProj.setObjectName("btnAddCurrEnvToProj")
        self.verticalLayout_4.addWidget(self.btnAddCurrEnvToProj)
        self.btnSaveChangesToProj = QtWidgets.QPushButton(self.tabROIs)
        self.btnSaveChangesToProj.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.btnSaveChangesToProj.sizePolicy().hasHeightForWidth())
        self.btnSaveChangesToProj.setSizePolicy(sizePolicy)
        self.btnSaveChangesToProj.setMinimumSize(QtCore.QSize(0, 26))
        self.btnSaveChangesToProj.setMaximumSize(QtCore.QSize(100, 30))
        self.btnSaveChangesToProj.setObjectName("btnSaveChangesToProj")
        self.verticalLayout_4.addWidget(self.btnSaveChangesToProj)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 3, 2, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.checkBoxShowAllROIs = QtWidgets.QCheckBox(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowAllROIs.sizePolicy().hasHeightForWidth())
        self.checkBoxShowAllROIs.setSizePolicy(sizePolicy)
        self.checkBoxShowAllROIs.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBoxShowAllROIs.setChecked(True)
        self.checkBoxShowAllROIs.setObjectName("checkBoxShowAllROIs")
        self.horizontalLayout_7.addWidget(self.checkBoxShowAllROIs)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listwROIs = QtWidgets.QListWidget(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwROIs.sizePolicy().hasHeightForWidth())
        self.listwROIs.setSizePolicy(sizePolicy)
        self.listwROIs.setMinimumSize(QtCore.QSize(0, 0))
        self.listwROIs.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listwROIs.setObjectName("listwROIs")
        self.horizontalLayout_8.addWidget(self.listwROIs)
        self.listwROIDefs = QtWidgets.QListWidget(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwROIDefs.sizePolicy().hasHeightForWidth())
        self.listwROIDefs.setSizePolicy(sizePolicy)
        self.listwROIDefs.setMinimumSize(QtCore.QSize(0, 0))
        self.listwROIDefs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listwROIDefs.setObjectName("listwROIDefs")
        self.horizontalLayout_8.addWidget(self.listwROIDefs)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 5, 1)
        self.textBoxComments = QtWidgets.QPlainTextEdit(self.tabROIs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBoxComments.sizePolicy().hasHeightForWidth())
        self.textBoxComments.setSizePolicy(sizePolicy)
        self.textBoxComments.setObjectName("textBoxComments")
        self.gridLayout_2.addWidget(self.textBoxComments, 0, 2, 5, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem17, 0, 1, 1, 1)
        self.lineEdROIDef = QtWidgets.QLineEdit(self.tabROIs)
        self.lineEdROIDef.setObjectName("lineEdROIDef")
        self.gridLayout_2.addWidget(self.lineEdROIDef, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tabROIs, "")
        self.gridLayout_10.addWidget(self.splitterHighest, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.sliderStrides.valueChanged['int'].connect(self.labelStridesValue.setNum)
        self.sliderOverlaps.valueChanged['int'].connect(self.labelOverlapsValue.setNum)
        self.rigMotCheckBox.toggled['bool'].connect(self.btnAddToBatch.setEnabled)
        self.lineEdROIDef.returnPressed.connect(self.BtnSetROIDefs.click)
        self.lineEdAnimalID.returnPressed.connect(self.btnSetID.click)
        self.lineEdTrialID.returnPressed.connect(self.btnSetID.click)
        self.lineEdGenotype.returnPressed.connect(self.btnSetID.click)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tabWidget, self.roiPlot)
        Form.setTabOrder(self.roiPlot, self.histogram)
        Form.setTabOrder(self.histogram, self.graphicsView)
        Form.setTabOrder(self.graphicsView, self.comboBoxStimMaps)
        Form.setTabOrder(self.comboBoxStimMaps, self.listwMesfile)
        Form.setTabOrder(self.listwMesfile, self.btnOpenTiff)
        Form.setTabOrder(self.btnOpenTiff, self.listwTiffs)
        Form.setTabOrder(self.listwTiffs, self.listwSplits)
        Form.setTabOrder(self.listwSplits, self.listwBatch)
        Form.setTabOrder(self.listwBatch, self.listwDenoised)
        Form.setTabOrder(self.listwDenoised, self.btnCrop)
        Form.setTabOrder(self.btnCrop, self.btnAddROI)
        Form.setTabOrder(self.btnAddROI, self.btnResetScale)
        Form.setTabOrder(self.btnResetScale, self.lineEdAnimalID)
        Form.setTabOrder(self.lineEdAnimalID, self.lineEdTrialID)
        Form.setTabOrder(self.lineEdTrialID, self.lineEdGenotype)
        Form.setTabOrder(self.lineEdGenotype, self.btnSetID)
        Form.setTabOrder(self.btnSetID, self.rigMotCheckBox)
        Form.setTabOrder(self.rigMotCheckBox, self.btnMeasureDistance)
        Form.setTabOrder(self.btnMeasureDistance, self.spinboxX)
        Form.setTabOrder(self.spinboxX, self.spinboxY)
        Form.setTabOrder(self.spinboxY, self.spinboxThreads)
        Form.setTabOrder(self.spinboxThreads, self.spinboxIter)
        Form.setTabOrder(self.spinboxIter, self.spinboxUpsample)
        Form.setTabOrder(self.spinboxUpsample, self.spinboxMaxDev)
        Form.setTabOrder(self.spinboxMaxDev, self.sliderStrides)
        Form.setTabOrder(self.sliderStrides, self.sliderOverlaps)
        Form.setTabOrder(self.sliderOverlaps, self.btnAddToBatch)
        Form.setTabOrder(self.btnAddToBatch, self.lineEdROIDef)
        Form.setTabOrder(self.lineEdROIDef, self.BtnSetROIDefs)
        Form.setTabOrder(self.BtnSetROIDefs, self.textBoxComments)
        Form.setTabOrder(self.textBoxComments, self.btnAddCurrEnvToProj)
        Form.setTabOrder(self.btnAddCurrEnvToProj, self.btnSaveChangesToProj)
        Form.setTabOrder(self.btnSaveChangesToProj, self.checkBoxShowAllROIs)
        Form.setTabOrder(self.checkBoxShowAllROIs, self.listwROIs)
        Form.setTabOrder(self.listwROIs, self.listwROIDefs)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mesfile_label.setText(_translate("Form", "MES file contents:"))
        self.btnOpenMesFiles.setText(_translate("Form", "Open mes file"))
        self.btnTiffPage.setText(_translate("Form", "Tiff Files >>"))
        self.btnOpenTiff.setText(_translate("Form", "Open tiff files"))
        self.btnSplitsPage.setText(_translate("Form", "Splits >>"))
        self.imgs_list_label.setText(_translate("Form", "Images/stacks:"))
        self.imgs_list_label_2.setText(_translate("Form", "Splits of seq:"))
        self.btnMesPage.setText(_translate("Form", "Mes Files >>"))
        self.btnOpenBatch.setText(_translate("Form", "Open Batch"))
        self.btnMCPage.setText(_translate("Form", "motion corrected >>"))
        self.batchLabel.setText(_translate("Form", "Batch"))
        self.btnStartBatch.setText(_translate("Form", "Start Batch"))
        self.btnRemoveFromBatch.setText(_translate("Form", "Remove"))
        self.motioncorrlistLabel.setText(_translate("Form", "Motion Corrected"))
        self.btnDenPage.setText(_translate("Form", "denoised >>"))
        self.btnMotCorSearchDir.setText(_translate("Form", "Search in dir"))
        self.btnBatchPage.setText(_translate("Form", "batch >>"))
        self.denoisedlistLabel.setText(_translate("Form", "Denoised"))
        self.btnChangeSMap.setToolTip(_translate("Form", "<html><head/><body><p>Change the Stimulus Map.</p></body></html>"))
        self.btnChangeSMap.setText(_translate("Form", "Change sMap"))
        self.btnImportSMap.setText(_translate("Form", "Import sMap"))
        self.btnResetSMap.setToolTip(_translate("Form", "<html><head/><body><p>Reset the Stimulus Map to the one set for this mes file.</p></body></html>"))
        self.btnResetSMap.setText(_translate("Form", "Reset sMap"))
        self.btnResetScale.setToolTip(_translate("Form", "Reset scale of the image and timeline"))
        self.btnResetScale.setText(_translate("Form", "Reset scale"))
        self.btnCrop.setText(_translate("Form", "Crop"))
        self.btnAddROI.setToolTip(_translate("Form", "Add ROI to the image"))
        self.btnAddROI.setText(_translate("Form", "+ ROI"))
        self.btnPlot.setToolTip(_translate("Form", "Add ROI to the image"))
        self.btnPlot.setText(_translate("Form", "Plot"))
        self.btnEditMetaData.setToolTip(_translate("Form", "Add ROI to the image"))
        self.btnEditMetaData.setText(_translate("Form", "Edit meta-data"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("Form", "Standard tools"))
        self.btnSplitSeq.setText(_translate("Form", "Split seq"))
        self.btnDoneSplitSeqs.setText(_translate("Form", "Add to Proj"))
        self.btnPlotSplits.setText(_translate("Form", "Plot from splits"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), _translate("Form", "Split-seq tools"))
        self.label_6.setText(_translate("Form", "Stimulus Maps:"))
        self.comboBoxStimMaps.setToolTip(_translate("Form", "Choose a Stimulus Map to display on the Timeline"))
        self.btnExportWorkEnv.setText(_translate("Form", "Export workEnv"))
        self.btnAbort.setText(_translate("Form", "Abort"))
        self.lineEdAnimalID.setPlaceholderText(_translate("Form", "Animal ID"))
        self.lineEdTrialID.setPlaceholderText(_translate("Form", "Trial ID"))
        self.lineEdGenotype.setPlaceholderText(_translate("Form", "Genotype"))
        self.btnSetID.setText(_translate("Form", "Set"))
        self.rigMotCheckBox.setText(_translate("Form", "Motion Correction"))
        self.btnMeasureDistance.setText(_translate("Form", "Measure"))
        self.label_7.setText(_translate("Form", " max shifts X (pixels): "))
        self.label_11.setText(_translate("Form", " max shifts Y (pixels): "))
        self.label_12.setText(_translate("Form", " threads: "))
        self.label_2.setText(_translate("Form", " iterations for rigid: "))
        self.label_8.setText(_translate("Form", " upsample grid:"))
        self.label_3.setText(_translate("Form", " max deviation from rigid:"))
        self.label_4.setText(_translate("Form", "strides (pixels): "))
        self.label_5.setText(_translate("Form", "overlaps (pixels): "))
        self.btnShowQuilt.setText(_translate("Form", "Show Quilt"))
        self.btnAddToBatch.setText(_translate("Form", "Add to batch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatchParams), _translate("Form", "Batch Params"))
        self.BtnSetROIDefs.setText(_translate("Form", "Set ROI tag"))
        self.btnAddCurrEnvToProj.setText(_translate("Form", "Add to Project"))
        self.btnSaveChangesToProj.setText(_translate("Form", "Save changes"))
        self.label.setText(_translate("Form", "ROIs:   "))
        self.checkBoxShowAllROIs.setToolTip(_translate("Form", "Show all ROIs or just the one selected from the list"))
        self.checkBoxShowAllROIs.setText(_translate("Form", "Show all on image"))
        self.listwROIs.setToolTip(_translate("Form", "ARRAYS START AT ZERO!"))
        self.listwROIDefs.setToolTip(_translate("Form", "ROI Definitions pulled from your config file.\n"
"To add more definitions go to Main Menu -> Edit -> Project Configuration"))
        self.textBoxComments.setPlaceholderText(_translate("Form", "Comments"))
        self.lineEdROIDef.setPlaceholderText(_translate("Form", "Add Tag to ROI Definition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabROIs), _translate("Form", "ROIs"))

from ..widgets.GraphicsView import GraphicsView
from ..widgets.HistogramLUTWidget import HistogramLUTWidget
from pyqtgraphCore import PlotWidget
