# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.groups_tab = QtWidgets.QWidget()
        self.groups_tab.setObjectName("groups_tab")
        self.listwGroups = QtWidgets.QListWidget(self.groups_tab)
        self.listwGroups.setGeometry(QtCore.QRect(10, 10, 411, 391))
        self.listwGroups.setObjectName("listwGroups")
        self.tabWidget.addTab(self.groups_tab, "")
        self.curve_tab = QtWidgets.QWidget()
        self.curve_tab.setObjectName("curve_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.curve_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.curve_tab, "")
        self.violin_tab = QtWidgets.QWidget()
        self.violin_tab.setObjectName("violin_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.violin_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget.addTab(self.violin_tab, "")
        self.box_plot_tab = QtWidgets.QWidget()
        self.box_plot_tab.setObjectName("box_plot_tab")
        self.tabWidget.addTab(self.box_plot_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(250, 66))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.dockWidgetContents)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stack_page_transmission_history = QtWidgets.QWidget()
        self.stack_page_transmission_history.setObjectName("stack_page_transmission_history")
        self.stackedWidget.addWidget(self.stack_page_transmission_history)
        self.stack_page_matplotlib = QtWidgets.QWidget()
        self.stack_page_matplotlib.setObjectName("stack_page_matplotlib")
        self.stackedWidget.addWidget(self.stack_page_matplotlib)
        self.stack_page_box_plots = QtWidgets.QWidget()
        self.stack_page_box_plots.setObjectName("stack_page_box_plots")
        self.stackedWidget.addWidget(self.stack_page_box_plots)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockConsole = QtWidgets.QDockWidget(MainWindow)
        self.dockConsole.setMinimumSize(QtCore.QSize(59, 200))
        self.dockConsole.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockConsole.setObjectName("dockConsole")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.dockConsole.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockConsole)
        self.actionSave_Statistics_DataFrame = QtWidgets.QAction(MainWindow)
        self.actionSave_Statistics_DataFrame.setObjectName("actionSave_Statistics_DataFrame")
        self.actionSave_Group_Transmissions = QtWidgets.QAction(MainWindow)
        self.actionSave_Group_Transmissions.setObjectName("actionSave_Group_Transmissions")
        self.actionLoad_Groups = QtWidgets.QAction(MainWindow)
        self.actionLoad_Groups.setObjectName("actionLoad_Groups")
        self.actionConsole = QtWidgets.QAction(MainWindow)
        self.actionConsole.setCheckable(True)
        self.actionConsole.setObjectName("actionConsole")
        self.actionSave_Incoming_Transmissions = QtWidgets.QAction(MainWindow)
        self.actionSave_Incoming_Transmissions.setObjectName("actionSave_Incoming_Transmissions")
        self.actionOpen_Statistics_DataFrame = QtWidgets.QAction(MainWindow)
        self.actionOpen_Statistics_DataFrame.setObjectName("actionOpen_Statistics_DataFrame")
        self.actionControls_Dock = QtWidgets.QAction(MainWindow)
        self.actionControls_Dock.setCheckable(True)
        self.actionControls_Dock.setChecked(True)
        self.actionControls_Dock.setObjectName("actionControls_Dock")
        self.menuFile.addAction(self.actionSave_Statistics_DataFrame)
        self.menuFile.addAction(self.actionOpen_Statistics_DataFrame)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Group_Transmissions)
        self.menuFile.addAction(self.actionLoad_Groups)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Incoming_Transmissions)
        self.menuView.addAction(self.actionConsole)
        self.menuView.addAction(self.actionControls_Dock)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.actionConsole.toggled['bool'].connect(self.dockConsole.setVisible)
        self.actionControls_Dock.toggled['bool'].connect(self.dockWidget.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groups_tab), _translate("MainWindow", "Groups"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.curve_tab), _translate("MainWindow", "Curves"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.violin_tab), _translate("MainWindow", "Violin Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.box_plot_tab), _translate("MainWindow", "Box Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.dockConsole.setWindowTitle(_translate("MainWindow", "Statistics Console"))
        self.actionSave_Statistics_DataFrame.setText(_translate("MainWindow", "Save Statistics DataFrame"))
        self.actionSave_Group_Transmissions.setText(_translate("MainWindow", "Save Groups"))
        self.actionLoad_Groups.setText(_translate("MainWindow", "Load Groups"))
        self.actionConsole.setText(_translate("MainWindow", "Console"))
        self.actionSave_Incoming_Transmissions.setText(_translate("MainWindow", "Save Incoming Raw Transmissions"))
        self.actionOpen_Statistics_DataFrame.setText(_translate("MainWindow", "Open Statistics DataFrame"))
        self.actionControls_Dock.setText(_translate("MainWindow", "Controls Dock"))

