# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_files/beeswarm_plot_controls.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BeeswarmControls(object):
    def setupUi(self, BeeswarmControls):
        BeeswarmControls.setObjectName("BeeswarmControls")
        BeeswarmControls.resize(279, 573)
        self.btnApply = QtWidgets.QPushButton(BeeswarmControls)
        self.btnApply.setGeometry(QtCore.QRect(9, 404, 80, 26))
        self.btnApply.setObjectName("btnApply")
        self.btnEditColor = QtWidgets.QPushButton(BeeswarmControls)
        self.btnEditColor.setGeometry(QtCore.QRect(9, 323, 80, 26))
        self.btnEditColor.setObjectName("btnEditColor")
        self.label = QtWidgets.QLabel(BeeswarmControls)
        self.label.setGeometry(QtCore.QRect(9, 9, 82, 18))
        self.label.setObjectName("label")
        self.horizontalSliderSpotSize = QtWidgets.QSlider(BeeswarmControls)
        self.horizontalSliderSpotSize.setGeometry(QtCore.QRect(9, 383, 261, 16))
        self.horizontalSliderSpotSize.setMinimum(1)
        self.horizontalSliderSpotSize.setProperty("value", 10)
        self.horizontalSliderSpotSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSpotSize.setObjectName("horizontalSliderSpotSize")
        self.label_2 = QtWidgets.QLabel(BeeswarmControls)
        self.label_2.setGeometry(QtCore.QRect(9, 231, 99, 18))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(BeeswarmControls)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 289, 261, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonGroupByTransmissions = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonGroupByTransmissions.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radioButtonGroupByTransmissions.setObjectName("radioButtonGroupByTransmissions")
        self.horizontalLayout_2.addWidget(self.radioButtonGroupByTransmissions)
        self.btnSetIncomingTransmissionsNames = QtWidgets.QPushButton(self.layoutWidget)
        self.btnSetIncomingTransmissionsNames.setObjectName("btnSetIncomingTransmissionsNames")
        self.horizontalLayout_2.addWidget(self.btnSetIncomingTransmissionsNames)
        self.listWidgetDataColumns = QtWidgets.QListWidget(BeeswarmControls)
        self.listWidgetDataColumns.setGeometry(QtCore.QRect(9, 33, 261, 192))
        self.listWidgetDataColumns.setAlternatingRowColors(True)
        self.listWidgetDataColumns.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidgetDataColumns.setObjectName("listWidgetDataColumns")
        self.layoutWidget_2 = QtWidgets.QWidget(BeeswarmControls)
        self.layoutWidget_2.setGeometry(QtCore.QRect(9, 355, 261, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.labelSpotSize = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelSpotSize.setObjectName("labelSpotSize")
        self.horizontalLayout_3.addWidget(self.labelSpotSize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.layoutWidget_3 = QtWidgets.QWidget(BeeswarmControls)
        self.layoutWidget_3.setGeometry(QtCore.QRect(9, 255, 261, 28))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonGroupBySingleColumn = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.radioButtonGroupBySingleColumn.setMaximumSize(QtCore.QSize(16, 16777215))
        self.radioButtonGroupBySingleColumn.setText("")
        self.radioButtonGroupBySingleColumn.setObjectName("radioButtonGroupBySingleColumn")
        self.horizontalLayout.addWidget(self.radioButtonGroupBySingleColumn)
        self.comboBoxGrouping = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBoxGrouping.setObjectName("comboBoxGrouping")
        self.horizontalLayout.addWidget(self.comboBoxGrouping)

        self.retranslateUi(BeeswarmControls)
        self.horizontalSliderSpotSize.valueChanged['int'].connect(self.labelSpotSize.setNum)
        QtCore.QMetaObject.connectSlotsByName(BeeswarmControls)

    def retranslateUi(self, BeeswarmControls):
        _translate = QtCore.QCoreApplication.translate
        BeeswarmControls.setWindowTitle(_translate("BeeswarmControls", "Form"))
        self.btnApply.setText(_translate("BeeswarmControls", "Apply all"))
        self.btnEditColor.setText(_translate("BeeswarmControls", "Edit colors"))
        self.label.setText(_translate("BeeswarmControls", "Data columns"))
        self.label_2.setText(_translate("BeeswarmControls", "Group based on:"))
        self.radioButtonGroupByTransmissions.setText(_translate("BeeswarmControls", "Incoming transmissions"))
        self.btnSetIncomingTransmissionsNames.setText(_translate("BeeswarmControls", "Set Names"))
        self.label_3.setText(_translate("BeeswarmControls", "Spot size: "))
        self.labelSpotSize.setText(_translate("BeeswarmControls", "10"))

