#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 2 2017

@author: kushal

Chatzigeorgiou Group
Sars International Centre for Marine Molecular Biology

GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007

"""

import configparser

config = configparser.RawConfigParser(allow_no_value=True)
config.optionxform = str

def newConfig(path):
    defaultInclude = ['SampleID', 'Date']
    config['INCLUDE'] = dict.fromkeys(defaultInclude)

    defaultExclude = ['CurvePath', 'ImgInfoPath', 'ImgPath']
    config['EXCLUDE'] = dict.fromkeys(defaultExclude)

    config['ROI_DEFS'] = {}

    config['STIM_DEFS'] = {}

    with open(path, 'w') as configfile:
        config.write(configfile)
    return config

def openConfig(path):
    return config.read(path)

def saveConfig(path, config):
    with open(path, 'w') as configfile:
        configfile.write(path)