# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configwindow_template.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(599, 613)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(593, 610))
        Form.setMaximumSize(QtCore.QSize(599, 623))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.listwInclude = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwInclude.sizePolicy().hasHeightForWidth())
        self.listwInclude.setSizePolicy(sizePolicy)
        self.listwInclude.setDragEnabled(True)
        self.listwInclude.setDragDropOverwriteMode(False)
        self.listwInclude.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listwInclude.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listwInclude.setAlternatingRowColors(True)
        self.listwInclude.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listwInclude.setObjectName("listwInclude")
        self.gridLayout_3.addWidget(self.listwInclude, 1, 0, 1, 3)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 0, 1, 1)
        self.listwExclude = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwExclude.sizePolicy().hasHeightForWidth())
        self.listwExclude.setSizePolicy(sizePolicy)
        self.listwExclude.setDragEnabled(True)
        self.listwExclude.setDragDropOverwriteMode(False)
        self.listwExclude.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listwExclude.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listwExclude.setAlternatingRowColors(True)
        self.listwExclude.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listwExclude.setObjectName("listwExclude")
        self.gridLayout_4.addWidget(self.listwExclude, 1, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(238, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(238, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 1, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listwROIDefs = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwROIDefs.sizePolicy().hasHeightForWidth())
        self.listwROIDefs.setSizePolicy(sizePolicy)
        self.listwROIDefs.setAlternatingRowColors(True)
        self.listwROIDefs.setObjectName("listwROIDefs")
        self.verticalLayout_2.addWidget(self.listwROIDefs)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdNewROIDef = QtWidgets.QLineEdit(Form)
        self.lineEdNewROIDef.setObjectName("lineEdNewROIDef")
        self.horizontalLayout_2.addWidget(self.lineEdNewROIDef)
        self.btnAddNewROICol = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddNewROICol.sizePolicy().hasHeightForWidth())
        self.btnAddNewROICol.setSizePolicy(sizePolicy)
        self.btnAddNewROICol.setMaximumSize(QtCore.QSize(51, 16777215))
        self.btnAddNewROICol.setObjectName("btnAddNewROICol")
        self.horizontalLayout_2.addWidget(self.btnAddNewROICol)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(28, 238, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem14 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.listwStimDefs = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listwStimDefs.sizePolicy().hasHeightForWidth())
        self.listwStimDefs.setSizePolicy(sizePolicy)
        self.listwStimDefs.setAlternatingRowColors(True)
        self.listwStimDefs.setObjectName("listwStimDefs")
        self.verticalLayout.addWidget(self.listwStimDefs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdNewStimCol = QtWidgets.QLineEdit(Form)
        self.lineEdNewStimCol.setObjectName("lineEdNewStimCol")
        self.horizontalLayout.addWidget(self.lineEdNewStimCol)
        self.btnAddNewStimCol = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddNewStimCol.sizePolicy().hasHeightForWidth())
        self.btnAddNewStimCol.setSizePolicy(sizePolicy)
        self.btnAddNewStimCol.setMaximumSize(QtCore.QSize(51, 16777215))
        self.btnAddNewStimCol.setObjectName("btnAddNewStimCol")
        self.horizontalLayout.addWidget(self.btnAddNewStimCol)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem15 = QtWidgets.QSpacerItem(558, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem16 = QtWidgets.QSpacerItem(338, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnClose = QtWidgets.QPushButton(Form)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_6.addWidget(self.btnClose)
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setMinimumSize(QtCore.QSize(92, 0))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_6.addWidget(self.btnSave)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)

        self.retranslateUi(Form)
        self.lineEdNewROIDef.returnPressed.connect(self.btnAddNewROICol.click)
        self.lineEdNewStimCol.returnPressed.connect(self.btnAddNewStimCol.click)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.listwInclude, self.listwExclude)
        Form.setTabOrder(self.listwExclude, self.listwROIDefs)
        Form.setTabOrder(self.listwROIDefs, self.listwStimDefs)
        Form.setTabOrder(self.listwStimDefs, self.lineEdNewROIDef)
        Form.setTabOrder(self.lineEdNewROIDef, self.btnAddNewROICol)
        Form.setTabOrder(self.btnAddNewROICol, self.lineEdNewStimCol)
        Form.setTabOrder(self.lineEdNewStimCol, self.btnAddNewStimCol)
        Form.setTabOrder(self.btnAddNewStimCol, self.btnSave)
        Form.setTabOrder(self.btnSave, self.btnClose)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dataframe Config"))
        self.label.setText(_translate("Form", "Drag & Drop to include or exclude columns in the Project Browser View"))
        self.label_2.setText(_translate("Form", "Include"))
        self.label_3.setText(_translate("Form", "Exclude"))
        self.label_4.setText(_translate("Form", "ROI Definition Columns"))
        self.lineEdNewROIDef.setPlaceholderText(_translate("Form", "Enter New ROI Column Name"))
        self.btnAddNewROICol.setText(_translate("Form", "Add"))
        self.label_5.setText(_translate("Form", "Stimulus Definition Columns"))
        self.lineEdNewStimCol.setPlaceholderText(_translate("Form", "Enter New Stim Column Name"))
        self.btnAddNewStimCol.setText(_translate("Form", "Add"))
        self.btnClose.setText(_translate("Form", "Close"))
        self.btnSave.setText(_translate("Form", "Save and apply"))

