# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjBrowser_template.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(931, 775)
        self.BtnConsole = QtWidgets.QPushButton(Form)
        self.BtnConsole.setGeometry(QtCore.QRect(10, 740, 80, 26))
        self.BtnConsole.setObjectName("BtnConsole")
        self.BtnJupyter = QtWidgets.QPushButton(Form)
        self.BtnJupyter.setGeometry(QtCore.QRect(100, 740, 101, 26))
        self.BtnJupyter.setObjectName("BtnJupyter")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 460, 911, 262))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BtnPlot = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnPlot.setEnabled(False)
        self.BtnPlot.setObjectName("BtnPlot")
        self.horizontalLayout_3.addWidget(self.BtnPlot)
        self.BtnResetFilters = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnResetFilters.setEnabled(False)
        self.BtnResetFilters.setObjectName("BtnResetFilters")
        self.horizontalLayout_3.addWidget(self.BtnResetFilters)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.curvesPlotWidget = PlotWidget(self.layoutWidget)
        self.curvesPlotWidget.setObjectName("curvesPlotWidget")
        self.horizontalLayout.addWidget(self.curvesPlotWidget)
        self.boxPlotPlotWidget = PlotWidget(self.layoutWidget)
        self.boxPlotPlotWidget.setObjectName("boxPlotPlotWidget")
        self.horizontalLayout.addWidget(self.boxPlotPlotWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widgetMasterColumnsContainer = QtWidgets.QWidget(Form)
        self.widgetMasterColumnsContainer.setGeometry(QtCore.QRect(0, 0, 241, 331))
        self.widgetMasterColumnsContainer.setObjectName("widgetMasterColumnsContainer")
        self.widget = QtWidgets.QWidget(self.widgetMasterColumnsContainer)
        self.widget.setGeometry(QtCore.QRect(10, 10, 231, 321))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelColumn_ = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelColumn_.setFont(font)
        self.labelColumn_.setAccessibleDescription("")
        self.labelColumn_.setObjectName("labelColumn_")
        self.gridLayout.addWidget(self.labelColumn_, 0, 0, 1, 1)
        self.rad_ = QtWidgets.QRadioButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rad_.sizePolicy().hasHeightForWidth())
        self.rad_.setSizePolicy(sizePolicy)
        self.rad_.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rad_.setAccessibleDescription("")
        self.rad_.setChecked(False)
        self.rad_.setObjectName("rad_")
        self.gridLayout.addWidget(self.rad_, 0, 1, 1, 2)
        self.listw_ = QtWidgets.QListWidget(self.widget)
        self.listw_.setAccessibleDescription("")
        self.listw_.setObjectName("listw_")
        self.gridLayout.addWidget(self.listw_, 1, 0, 1, 3)
        self.lineEdFilter_ = QtWidgets.QLineEdit(self.widget)
        self.lineEdFilter_.setAccessibleDescription("")
        self.lineEdFilter_.setInputMask("")
        self.lineEdFilter_.setObjectName("lineEdFilter_")
        self.gridLayout.addWidget(self.lineEdFilter_, 2, 0, 1, 1)
        self.BtnApply_ = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnApply_.sizePolicy().hasHeightForWidth())
        self.BtnApply_.setSizePolicy(sizePolicy)
        self.BtnApply_.setMaximumSize(QtCore.QSize(45, 16777215))
        self.BtnApply_.setAccessibleDescription("")
        self.BtnApply_.setObjectName("BtnApply_")
        self.gridLayout.addWidget(self.BtnApply_, 2, 1, 1, 1)
        self.BtnReset_ = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnReset_.sizePolicy().hasHeightForWidth())
        self.BtnReset_.setSizePolicy(sizePolicy)
        self.BtnReset_.setMaximumSize(QtCore.QSize(50, 16777215))
        self.BtnReset_.setAccessibleDescription("")
        self.BtnReset_.setObjectName("BtnReset_")
        self.gridLayout.addWidget(self.BtnReset_, 2, 2, 1, 1)
        self.widgetSetx0Container = QtWidgets.QWidget(Form)
        self.widgetSetx0Container.setGeometry(QtCore.QRect(20, 400, 201, 51))
        self.widgetSetx0Container.setObjectName("widgetSetx0Container")
        self.widget1 = QtWidgets.QWidget(self.widgetSetx0Container)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 196, 50))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.radTStart = QtWidgets.QRadioButton(self.widget1)
        self.radTStart.setChecked(False)
        self.radTStart.setObjectName("radTStart")
        self.gridLayout_3.addWidget(self.radTStart, 1, 0, 1, 1)
        self.radTEnd = QtWidgets.QRadioButton(self.widget1)
        self.radTEnd.setObjectName("radTEnd")
        self.gridLayout_3.addWidget(self.radTEnd, 1, 1, 1, 1)
        self.radTCenter = QtWidgets.QRadioButton(self.widget1)
        self.radTCenter.setObjectName("radTCenter")
        self.gridLayout_3.addWidget(self.radTCenter, 1, 2, 1, 1)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(10, 340, 231, 62))
        self.widget2.setObjectName("widget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.spinBoxTStart = QtWidgets.QDoubleSpinBox(self.widget2)
        self.spinBoxTStart.setMaximum(99900.0)
        self.spinBoxTStart.setObjectName("spinBoxTStart")
        self.gridLayout_2.addWidget(self.spinBoxTStart, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.spinBoxTEnd = QtWidgets.QDoubleSpinBox(self.widget2)
        self.spinBoxTEnd.setObjectName("spinBoxTEnd")
        self.gridLayout_2.addWidget(self.spinBoxTEnd, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BtnConsole.setText(_translate("Form", "Console"))
        self.BtnJupyter.setText(_translate("Form", "Send to Jupyter"))
        self.BtnPlot.setText(_translate("Form", "Plot!"))
        self.BtnResetFilters.setText(_translate("Form", "Reset Filters"))
        self.labelColumn_.setText(_translate("Form", "TextLabel"))
        self.rad_.setText(_translate("Form", "Unique"))
        self.lineEdFilter_.setPlaceholderText(_translate("Form", "Filter"))
        self.BtnApply_.setText(_translate("Form", "Apply"))
        self.BtnReset_.setText(_translate("Form", "Reset"))
        self.label_4.setText(_translate("Form", "Set x0 ="))
        self.radTStart.setText(_translate("Form", "tStart"))
        self.radTEnd.setText(_translate("Form", "tEnd"))
        self.radTCenter.setText(_translate("Form", "tCenter"))
        self.label_3.setText(_translate("Form", "Set offsets: "))
        self.label.setText(_translate("Form", "tStart (ms): "))
        self.label_2.setText(_translate("Form", "tEnd (ms): "))

from pyqtgraphCore import PlotWidget
