# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stimMap_template.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form, voltList):
        Form.setObjectName("Form")
        Form.resize(719, 478)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(695, 450))
        self.setMapBtn = QtWidgets.QPushButton(Form)
        self.setMapBtn.setGeometry(QtCore.QRect(501, 382, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.setMapBtn.setFont(font)
        self.setMapBtn.setObjectName("setMapBtn")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 350, 357, 86))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 2, 1, 1)
        self.addtoProjBtn = QtWidgets.QPushButton(self.widget)
        self.addtoProjBtn.setObjectName("addtoProjBtn")
        self.gridLayout_4.addWidget(self.addtoProjBtn, 2, 3, 1, 1)
        self.stimLine = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stimLine.sizePolicy().hasHeightForWidth())
        self.stimLine.setSizePolicy(sizePolicy)
        self.stimLine.setObjectName("stimLine")
        self.gridLayout_4.addWidget(self.stimLine, 2, 0, 1, 2)
        self.substimLine = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substimLine.sizePolicy().hasHeightForWidth())
        self.substimLine.setSizePolicy(sizePolicy)
        self.substimLine.setObjectName("substimLine")
        self.gridLayout_4.addWidget(self.substimLine, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 4)
        self.addedNewLabel = QtWidgets.QLabel(self.widget)
        self.addedNewLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.addedNewLabel.setFont(font)
        self.addedNewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addedNewLabel.setObjectName("addedNewLabel")
        self.gridLayout_4.addWidget(self.addedNewLabel, 1, 3, 1, 1)
        self.aux_1_title_label = QtWidgets.QLabel(Form)
        self.aux_1_title_label.setGeometry(QtCore.QRect(100, 20, 38, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.aux_1_title_label.setFont(font)
        self.aux_1_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.aux_1_title_label.setObjectName("aux_1_title_label")
#        self.widget1 = QtWidgets.QWidget(Form)
#        self.widget1.setGeometry(QtCore.QRect(30, 70, 221, 28))
#        self.widget1.setObjectName("widget1")
#        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
#        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
#        self.horizontalLayout.setObjectName("horizontalLayout")
#        self.aux_1_label_1 = QtWidgets.QLabel(self.widget1)
#        self.aux_1_label_1.setAlignment(QtCore.Qt.AlignCenter)
#        self.aux_1_label_1.setObjectName("aux_1_label_1")
#        self.horizontalLayout.addWidget(self.aux_1_label_1)
#        self.aux_1_stimBox_1 = QtWidgets.QComboBox(self.widget1)
#        self.aux_1_stimBox_1.setMaxVisibleItems(20)
#        self.aux_1_stimBox_1.setObjectName("aux_1_stimBox_1")
#        self.horizontalLayout.addWidget(self.aux_1_stimBox_1)
#        self.aux_1_colorBtn_1 = QtWidgets.QPushButton(self.widget1)
#        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
#        sizePolicy.setHorizontalStretch(0)
#        sizePolicy.setVerticalStretch(0)
#        sizePolicy.setHeightForWidth(self.aux_1_colorBtn_1.sizePolicy().hasHeightForWidth())
#        self.aux_1_colorBtn_1.setSizePolicy(sizePolicy)
#        self.aux_1_colorBtn_1.setObjectName("aux_1_colorBtn_1")
#        self.horizontalLayout.addWidget(self.aux_1_colorBtn_1)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(20, 50, 231, 20))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aux_1_voltage_header_label = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.aux_1_voltage_header_label.setFont(font)
        self.aux_1_voltage_header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.aux_1_voltage_header_label.setObjectName("aux_1_voltage_header_label")
        self.horizontalLayout_2.addWidget(self.aux_1_voltage_header_label)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)

        self.retranslateUi(Form)
        self.stimLine.textChanged['QString'].connect(self.addedNewLabel.hide)
        self.substimLine.textChanged['QString'].connect(self.addedNewLabel.hide)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.widgetList = []
        self.horizontalLayout = []
        self.aux_1_label_1 = []
        self.aux_1_stimBox_1 = []
        self.aux_1_colorBtn_1 = []
        
        for r in range(0,len(voltList)):
            self.widget.append(QtWidgets.QWidget(Form))
            self.widget[r].setGeometry(QtCore.QRect(30, (70 + r * 30), 401, 28))
            self.widget[r].setObjectName("widget"+str(r))
            self.horizontalLayoutRow.append(QtWidgets.QHBoxLayout(self.widget[r]))
            self.horizontalLayoutRow[r].setContentsMargins(0, 0, 0, 0)
            self.horizontalLayoutRow[r].setObjectName("horizontalLayoutRow"+str(r))
            self.aux_1_volt_label.append(QtWidgets.QLabel(self.widget[r]))
            self.aux_1_volt_label[r].setAlignment(QtCore.Qt.AlignCenter)
            self.aux_1_volt_label[r].setObjectName("aux_1_volt_label"+str())
            self.aux_1_volt_label[r].setText(str(voltList[r]))
            self.horizontalLayoutRow[r].addWidget(self.aux_1_volt_label[r])
            self.aux_1_stimBox.append(QtWidgets.QComboBox(self.widget[r]))
            self.aux_1_stimBox[r].setMinimumSize(QtCore.QSize(120, 0))
            self.aux_1_stimBox[r].setEditable(False)
            self.aux_1_stimBox[r].setCurrentText("")
            self.aux_1_stimBox[r].setMaxVisibleItems(20)
            self.aux_1_stimBox[r].setObjectName("aux_1_stimBox"+str(r))
            self.horizontalLayoutRow[r].addWidget(self.aux_1_stimBox[r])
            self.stimLineEdit.append(QtWidgets.QLineEdit(self.widget[r]))
            self.stimLineEdit[r].setInputMask("")
            self.stimLineEdit[r].setText("")
            self.stimLineEdit[r].setObjectName("stimLineEdit"+str(r))
            self.horizontalLayoutRow[r].addWidget(self.stimLineEdit[r])
            self.substimLineEdit.append(QtWidgets.QLineEdit(self.widget[r]))
            self.substimLineEdit[r].setInputMask("")
            self.substimLineEdit[r].setObjectName("substimLineEdit"+str(r))
            
            self.stimLineEdit[r].setPlaceholderText("New Stim")
            self.substimLineEdit[r].setPlaceholderText("Sub-stim")
            
            self.horizontalLayoutRow[r].addWidget(self.substimLineEdit[r])
            self.aux_1_colorBtn.append(QtWidgets.QPushButton(self.widget[r]))
#            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
#            sizePolicy.setHorizontalStretch(40)
#            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.aux_1_colorBtn[r].sizePolicy().hasHeightForWidth())
            self.aux_1_colorBtn[r].setSizePolicy(sizePolicy)
            self.aux_1_colorBtn[r].setMinimumSize(QtCore.QSize(40, 0))
            self.aux_1_colorBtn[r].setObjectName("aux_1_colorBtn"+str(r))
            self.aux_1_colorBtn[r].setText("Auto")
            self.horizontalLayoutRow[r].addWidget(self.aux_1_colorBtn[r])
        
#        for r in range(0,len(voltList)):
#            self.widgetList.append(QtWidgets.QWidget(Form))
#            self.widgetList[r].setGeometry(QtCore.QRect(25, (70 + r * 35), 221, 28))
#            self.widgetList[r].setObjectName("widget"+str(r))
#            self.horizontalLayout.append(QtWidgets.QHBoxLayout(self.widgetList[r]))
#            self.horizontalLayout[r].setContentsMargins(0, 0, 0, 0)
#            self.horizontalLayout[r].setObjectName("horizontalLayout"+str(r))
#            self.aux_1_label_1.append(QtWidgets.QLabel(self.widgetList[r]))
#            self.aux_1_label_1[r].setAlignment(QtCore.Qt.AlignCenter)
#            self.aux_1_label_1[r].setObjectName("aux_1_label_1")
#            self.aux_1_label_1[r].setText(str(voltList[r]))
#            self.horizontalLayout[r].addWidget(self.aux_1_label_1[r])
#            self.aux_1_stimBox_1.append(QtWidgets.QComboBox(self.widgetList[r]))
#            self.aux_1_stimBox_1[r].setMaxVisibleItems(20)
#            self.aux_1_stimBox_1[r].setObjectName("aux_1_stimBox_1"+str([r]))
#            self.horizontalLayout[r].addWidget(self.aux_1_stimBox_1[r])
#            self.aux_1_colorBtn_1.append(QtWidgets.QPushButton(self.widgetList[r]))
#            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
#            sizePolicy.setHorizontalStretch(0)
#            sizePolicy.setVerticalStretch(0)
#            sizePolicy.setHeightForWidth(self.aux_1_colorBtn_1[r].sizePolicy().hasHeightForWidth())
#            self.aux_1_colorBtn_1[r].setSizePolicy(sizePolicy)
#            self.aux_1_colorBtn_1[r].setObjectName("aux_1_colorBtn_1"+str([r]))
#            self.horizontalLayout[r].addWidget(self.aux_1_colorBtn_1[r])
        
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.setMapBtn.setText(_translate("Form", "Set Map"))
        self.label_15.setText(_translate("Form", "sub-Stimulus:"))
        self.addtoProjBtn.setText(_translate("Form", "Add to environment"))
        self.label_14.setText(_translate("Form", "Stimulus"))
        self.label_13.setText(_translate("Form", "Add New Stimulus:"))
        self.addedNewLabel.setText(_translate("Form", "Added!"))


