# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './welcome_window_pytemplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(32, 21, 752, 146))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btnNew = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNew.sizePolicy().hasHeightForWidth())
        self.btnNew.setSizePolicy(sizePolicy)
        self.btnNew.setMinimumSize(QtCore.QSize(131, 118))
        self.btnNew.setMaximumSize(QtCore.QSize(131, 118))
        self.btnNew.setAutoFillBackground(True)
        self.btnNew.setText("")
        self.btnNew.setFlat(False)
        self.btnNew.setObjectName("btnNew")
        self.verticalLayout.addWidget(self.btnNew)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.btnOpen = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpen.sizePolicy().hasHeightForWidth())
        self.btnOpen.setSizePolicy(sizePolicy)
        self.btnOpen.setMinimumSize(QtCore.QSize(131, 118))
        self.btnOpen.setMaximumSize(QtCore.QSize(131, 118))
        self.btnOpen.setAutoFillBackground(True)
        self.btnOpen.setText("")
        self.btnOpen.setFlat(False)
        self.btnOpen.setObjectName("btnOpen")
        self.verticalLayout_2.addWidget(self.btnOpen)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.listWidgetRecentProjects = QtWidgets.QListWidget(self.widget)
        self.listWidgetRecentProjects.setMinimumSize(QtCore.QSize(470, 118))
        self.listWidgetRecentProjects.setMaximumSize(QtCore.QSize(470, 118))
        self.listWidgetRecentProjects.setObjectName("listWidgetRecentProjects")
        self.verticalLayout_14.addWidget(self.listWidgetRecentProjects)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(31, 181, 760, 146))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.btnViewer = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnViewer.sizePolicy().hasHeightForWidth())
        self.btnViewer.setSizePolicy(sizePolicy)
        self.btnViewer.setMinimumSize(QtCore.QSize(131, 118))
        self.btnViewer.setMaximumSize(QtCore.QSize(131, 118))
        self.btnViewer.setAutoFillBackground(True)
        self.btnViewer.setText("")
        self.btnViewer.setFlat(False)
        self.btnViewer.setObjectName("btnViewer")
        self.verticalLayout_4.addWidget(self.btnViewer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.listWidgetViewers = QtWidgets.QListWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetViewers.sizePolicy().hasHeightForWidth())
        self.listWidgetViewers.setSizePolicy(sizePolicy)
        self.listWidgetViewers.setMinimumSize(QtCore.QSize(61, 118))
        self.listWidgetViewers.setMaximumSize(QtCore.QSize(61, 118))
        self.listWidgetViewers.setObjectName("listWidgetViewers")
        self.verticalLayout_5.addWidget(self.listWidgetViewers)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.btnFlowchart = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFlowchart.sizePolicy().hasHeightForWidth())
        self.btnFlowchart.setSizePolicy(sizePolicy)
        self.btnFlowchart.setMinimumSize(QtCore.QSize(131, 118))
        self.btnFlowchart.setMaximumSize(QtCore.QSize(131, 118))
        self.btnFlowchart.setAutoFillBackground(True)
        self.btnFlowchart.setText("")
        self.btnFlowchart.setFlat(False)
        self.btnFlowchart.setObjectName("btnFlowchart")
        self.verticalLayout_6.addWidget(self.btnFlowchart)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.listWidgetFlowcharts = QtWidgets.QListWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetFlowcharts.sizePolicy().hasHeightForWidth())
        self.listWidgetFlowcharts.setSizePolicy(sizePolicy)
        self.listWidgetFlowcharts.setMinimumSize(QtCore.QSize(61, 118))
        self.listWidgetFlowcharts.setMaximumSize(QtCore.QSize(61, 118))
        self.listWidgetFlowcharts.setObjectName("listWidgetFlowcharts")
        self.verticalLayout_7.addWidget(self.listWidgetFlowcharts)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.widget1)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.listWidgetPlots_5 = QtWidgets.QListWidget(self.widget1)
        self.listWidgetPlots_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetPlots_5.sizePolicy().hasHeightForWidth())
        self.listWidgetPlots_5.setSizePolicy(sizePolicy)
        self.listWidgetPlots_5.setMinimumSize(QtCore.QSize(331, 118))
        self.listWidgetPlots_5.setMaximumSize(QtCore.QSize(241, 118))
        self.listWidgetPlots_5.setObjectName("listWidgetPlots_5")
        self.verticalLayout_13.addWidget(self.listWidgetPlots_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(31, 340, 751, 146))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.btnPlot = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlot.sizePolicy().hasHeightForWidth())
        self.btnPlot.setSizePolicy(sizePolicy)
        self.btnPlot.setMinimumSize(QtCore.QSize(131, 118))
        self.btnPlot.setMaximumSize(QtCore.QSize(131, 118))
        self.btnPlot.setAutoFillBackground(True)
        self.btnPlot.setText("")
        self.btnPlot.setFlat(False)
        self.btnPlot.setObjectName("btnPlot")
        self.verticalLayout_8.addWidget(self.btnPlot)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.widget2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.listWidgetPlots = QtWidgets.QListWidget(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetPlots.sizePolicy().hasHeightForWidth())
        self.listWidgetPlots.setSizePolicy(sizePolicy)
        self.listWidgetPlots.setMinimumSize(QtCore.QSize(61, 118))
        self.listWidgetPlots.setMaximumSize(QtCore.QSize(61, 118))
        self.listWidgetPlots.setObjectName("listWidgetPlots")
        self.verticalLayout_9.addWidget(self.listWidgetPlots)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.listWidgetPlots_4 = QtWidgets.QListWidget(self.widget2)
        self.listWidgetPlots_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetPlots_4.sizePolicy().hasHeightForWidth())
        self.listWidgetPlots_4.setSizePolicy(sizePolicy)
        self.listWidgetPlots_4.setMinimumSize(QtCore.QSize(150, 118))
        self.listWidgetPlots_4.setMaximumSize(QtCore.QSize(150, 118))
        self.listWidgetPlots_4.setObjectName("listWidgetPlots_4")
        self.verticalLayout_12.addWidget(self.listWidgetPlots_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.line_2 = QtWidgets.QFrame(self.widget2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.btnClustering = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClustering.sizePolicy().hasHeightForWidth())
        self.btnClustering.setSizePolicy(sizePolicy)
        self.btnClustering.setMinimumSize(QtCore.QSize(131, 118))
        self.btnClustering.setMaximumSize(QtCore.QSize(131, 118))
        self.btnClustering.setAutoFillBackground(True)
        self.btnClustering.setText("")
        self.btnClustering.setFlat(False)
        self.btnClustering.setObjectName("btnClustering")
        self.verticalLayout_10.addWidget(self.btnClustering)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.listWidgetClustering = QtWidgets.QListWidget(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetClustering.sizePolicy().hasHeightForWidth())
        self.listWidgetClustering.setSizePolicy(sizePolicy)
        self.listWidgetClustering.setMinimumSize(QtCore.QSize(61, 118))
        self.listWidgetClustering.setMaximumSize(QtCore.QSize(61, 118))
        self.listWidgetClustering.setObjectName("listWidgetClustering")
        self.verticalLayout_11.addWidget(self.listWidgetClustering)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.listWidgetPlots_6 = QtWidgets.QListWidget(self.widget2)
        self.listWidgetPlots_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetPlots_6.sizePolicy().hasHeightForWidth())
        self.listWidgetPlots_6.setSizePolicy(sizePolicy)
        self.listWidgetPlots_6.setMinimumSize(QtCore.QSize(150, 118))
        self.listWidgetPlots_6.setMaximumSize(QtCore.QSize(150, 118))
        self.listWidgetPlots_6.setObjectName("listWidgetPlots_6")
        self.verticalLayout_3.addWidget(self.listWidgetPlots_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "New Project"))
        self.label_2.setText(_translate("MainWindow", "Open Project"))
        self.label_3.setText(_translate("MainWindow", "Recent Projects"))
        self.label_4.setText(_translate("MainWindow", "Viewer"))
        self.label_9.setText(_translate("MainWindow", "Running"))
        self.label_5.setText(_translate("MainWindow", "Flowchart"))
        self.label_10.setText(_translate("MainWindow", "Running"))
        self.label_13.setText(_translate("MainWindow", "In current project"))
        self.label_6.setText(_translate("MainWindow", "Plots"))
        self.label_11.setText(_translate("MainWindow", "Running"))
        self.label_12.setText(_translate("MainWindow", "In current project"))
        self.label_8.setText(_translate("MainWindow", "Clustering"))
        self.label_7.setText(_translate("MainWindow", "Running"))
        self.label_14.setText(_translate("MainWindow", "In current project"))

